outfit_options["glasses"] = {
  "/obj/item/clothing/glasses/sunglasses/spy": "sunglasses [sun_spy]",
  "/obj/item/clothing/glasses/sunglasses/reagent": "beer goggles [sunhudbeer]",
  "/obj/item/clothing/glasses/sunglasses/chemical": "science glasses [sunhudsci]",
  "/obj/item/clothing/glasses/sunglasses/garb/supergarb": "black giga gar glasses [supergarb]",
  "/obj/item/clothing/glasses/sunglasses/garb": "black gar glasses [garb]",
  "/obj/item/clothing/glasses/sunglasses/gar/supergar": "giga gar glasses [supergar]",
  "/obj/item/clothing/glasses/sunglasses/gar": "gar glasses [gar]",
  "/obj/item/clothing/glasses/sunglasses/big": "sunglasses [bigsunglasses]",
  "/obj/item/clothing/glasses/sunglasses": "sunglasses [sun]",
  "/obj/item/clothing/glasses/changeling": "flesh []",
  "/obj/item/clothing/glasses/hud/health/night/cultblind": "zealot's blindfold [blindfold]",
  "/obj/item/clothing/glasses/hud/health/night": "night vision health scanner HUD [healthhudnight]",
  "/obj/item/clothing/glasses/hud/health/sunglasses": "medical HUDSunglasses [sunhudmed]",
  "/obj/item/clothing/glasses/hud/health": "health scanner HUD [healthhud]",
  "/obj/item/clothing/glasses/hud/diagnostic/night": "night vision diagnostic HUD [diagnostichudnight]",
  "/obj/item/clothing/glasses/hud/diagnostic/sunglasses": "diagnostic sunglasses [sunhuddiag]",
  "/obj/item/clothing/glasses/hud/diagnostic": "diagnostic HUD [diagnostichud]",
  "/obj/item/clothing/glasses/hud/security/chameleon": "chameleon security HUD [securityhud]",
  "/obj/item/clothing/glasses/hud/security/sunglasses/eyepatch": "eyepatch HUD [hudpatch]",
  "/obj/item/clothing/glasses/hud/security/sunglasses/gars/supergars": "giga HUD gar glasses [supergars]",
  "/obj/item/clothing/glasses/hud/security/sunglasses/gars": "HUD gar glasses [gars]",
  "/obj/item/clothing/glasses/hud/security/sunglasses": "security HUDSunglasses [sunhudsec]",
  "/obj/item/clothing/glasses/hud/security/night": "night vision security HUD [securityhudnight]",
  "/obj/item/clothing/glasses/hud/security": "security HUD [securityhud]",
  "/obj/item/clothing/glasses/hud/toggle/thermal": "thermal HUD scanner [thermal]",
  "/obj/item/clothing/glasses/hud/toggle": "Toggle HUD []",
  "/obj/item/clothing/glasses/hud/spacecop/hidden": "sunglasses [undercover_cop]",
  "/obj/item/clothing/glasses/hud/spacecop": "police aviators [bigsunglasses]",
  "/obj/item/clothing/glasses/hud": "HUD []",
  "/obj/item/clothing/glasses/meson/truesight": "The Lens of Truesight [monocle]",
  "/obj/item/clothing/glasses/meson/night": "night vision meson scanner [nvgmeson]",
  "/obj/item/clothing/glasses/meson/gar": "gar mesons [garm]",
  "/obj/item/clothing/glasses/meson/engine/tray": "optical t-ray scanner [trayson-t-ray]",
  "/obj/item/clothing/glasses/meson/engine/shuttle": "shuttle region scanner [trayson-shuttle]",
  "/obj/item/clothing/glasses/meson/engine": "engineering scanner goggles [trayson-meson]",
  "/obj/item/clothing/glasses/meson": "optical meson scanner [meson]",
  "/obj/item/clothing/glasses/chameleon/broken": "Optical Meson Scanner [chameleon_broken]",
  "/obj/item/clothing/glasses/chameleon": "Optical Meson Scanner [chameleon]",
  "/obj/item/clothing/glasses/science": "science goggles [purple]",
  "/obj/item/clothing/glasses/night": "night vision goggles [night]",
  "/obj/item/clothing/glasses/eyepatch": "eyepatch [eyepatch]",
  "/obj/item/clothing/glasses/monocle": "monocle [monocle]",
  "/obj/item/clothing/glasses/material/mining/gar": "gar material scanner [garm]",
  "/obj/item/clothing/glasses/material/mining": "optical material scanner [mining]",
  "/obj/item/clothing/glasses/material": "optical material scanner [material]",
  "/obj/item/clothing/glasses/regular/jamjar": "jamjar glasses [jamjar_glasses]",
  "/obj/item/clothing/glasses/regular/hipster": "prescription glasses [hipster_glasses]",
  "/obj/item/clothing/glasses/regular/circle": "circle glasses [circle_glasses]",
  "/obj/item/clothing/glasses/regular": "prescription glasses [glasses]",
  "/obj/item/clothing/glasses/welding": "welding goggles [welding-g]",
  "/obj/item/clothing/glasses/blindfold/white": "blind personnel blindfold [blindfoldwhite]",
  "/obj/item/clothing/glasses/blindfold": "blindfold [blindfold]",
  "/obj/item/clothing/glasses/trickblindfold": "blindfold [trickblindfold]",
  "/obj/item/clothing/glasses/thermal/xray": "syndicate xray goggles [thermal]",
  "/obj/item/clothing/glasses/thermal/syndi": "chameleon thermals [thermal]",
  "/obj/item/clothing/glasses/thermal/monocle": "thermoncle [thermoncle]",
  "/obj/item/clothing/glasses/thermal/eyepatch": "optical thermal eyepatch [eyepatch]",
  "/obj/item/clothing/glasses/thermal": "optical thermal scanner [thermal]",
  "/obj/item/clothing/glasses/cold": "cold goggles [cold]",
  "/obj/item/clothing/glasses/heat": "heat goggles [heat]",
  "/obj/item/clothing/glasses/orange": "orange glasses [orangeglasses]",
  "/obj/item/clothing/glasses/red": "red glasses [redglasses]",
  "/obj/item/clothing/glasses/geist_gazers": "geist gazers [geist_gazers]",
  "/obj/item/clothing/glasses/psych": "psych glasses [psych_glasses]",
  "/obj/item/clothing/glasses/debug": "debug glasses [nvgmeson]",
  "/obj/item/clothing/glasses/godeye": "eye of god [godeye]",
  "/obj/item/clothing/glasses/prism_glasses": "prism glasses [prismglasses]",
  "/obj/item/clothing/glasses": "glasses []"
}
