outfit_options["gloves"] = {
  "/obj/item/clothing/gloves/boxing/green": "boxing gloves [boxinggreen]",
  "/obj/item/clothing/gloves/boxing/blue": "boxing gloves [boxingblue]",
  "/obj/item/clothing/gloves/boxing/yellow": "boxing gloves [boxingyellow]",
  "/obj/item/clothing/gloves/boxing": "boxing gloves [boxing]",
  "/obj/item/clothing/gloves/krav_maga/sec": "krav maga gloves [fightgloves]",
  "/obj/item/clothing/gloves/krav_maga/combatglovesplus": "combat gloves plus [black]",
  "/obj/item/clothing/gloves/krav_maga": "gloves []",
  "/obj/item/clothing/gloves/plate/red": "Plate Gauntlets [crusader-red]",
  "/obj/item/clothing/gloves/plate/blue": "Plate Gauntlets [crusader-blue]",
  "/obj/item/clothing/gloves/plate": "Plate Gauntlets [crusader]",
  "/obj/item/clothing/gloves/changeling": "flesh []",
  "/obj/item/clothing/gloves/chameleon/broken": "insulated gloves [yellow]",
  "/obj/item/clothing/gloves/chameleon": "insulated gloves [yellow]",
  "/obj/item/clothing/gloves/bracer": "bone bracers [bracers]",
  "/obj/item/clothing/gloves/botanic_leather/plasmaman": "botany envirogloves [botanyplasma]",
  "/obj/item/clothing/gloves/botanic_leather": "botanist's leather gloves [leather]",
  "/obj/item/clothing/gloves/color/yellow/sprayon": "spray-on insulated gloves [sprayon]",
  "/obj/item/clothing/gloves/color/yellow": "insulated gloves [yellow]",
  "/obj/item/clothing/gloves/color/fyellow/old": "worn out insulated gloves [yellow]",
  "/obj/item/clothing/gloves/color/fyellow": "budget insulated gloves [yellow]",
  "/obj/item/clothing/gloves/color/black": "black gloves [black]",
  "/obj/item/clothing/gloves/color/orange": "orange gloves [orange]",
  "/obj/item/clothing/gloves/color/red/insulated": "insulated gloves [red]",
  "/obj/item/clothing/gloves/color/red": "red gloves [red]",
  "/obj/item/clothing/gloves/color/rainbow": "rainbow gloves [rainbow]",
  "/obj/item/clothing/gloves/color/blue": "blue gloves [blue]",
  "/obj/item/clothing/gloves/color/purple": "purple gloves [purple]",
  "/obj/item/clothing/gloves/color/green": "green gloves [green]",
  "/obj/item/clothing/gloves/color/grey": "grey gloves [gray]",
  "/obj/item/clothing/gloves/color/light_brown": "light brown gloves [lightbrown]",
  "/obj/item/clothing/gloves/color/brown": "brown gloves [brown]",
  "/obj/item/clothing/gloves/color/captain": "captain's gloves [captain]",
  "/obj/item/clothing/gloves/color/chief_engineer": "advanced insulated gloves [ce_insuls]",
  "/obj/item/clothing/gloves/color/latex/nitrile": "nitrile gloves [nitrile]",
  "/obj/item/clothing/gloves/color/latex/engineering": "tinker's gloves [clockwork_gauntlets]",
  "/obj/item/clothing/gloves/color/latex": "latex gloves [latex]",
  "/obj/item/clothing/gloves/color/infiltrator": "infiltrator gloves [infiltrator]",
  "/obj/item/clothing/gloves/color/white": "white gloves [white]",
  "/obj/item/clothing/gloves/color/plasmaman/black": "black envirogloves [blackplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/plasmanitrile": "nitrile envirogloves [nitrile]",
  "/obj/item/clothing/gloves/color/plasmaman/white": "white envirogloves [whiteplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/robot": "roboticist envirogloves [robotplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/janny": "janitor envirogloves [jannyplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/cargo": "cargo envirogloves [cargoplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/engineer": "engineering envirogloves [engieplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/atmos": "atmos envirogloves [atmosplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/explorer": "explorer envirogloves [explorerplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/prototype": "prototype envirogloves [protoplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/clown": "clown envirogloves [clownplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/head_of_personnel": "head of personnel's envirogloves [hopplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/chief_engineer": "chief engineer's envirogloves [ceplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/research_director": "research director's envirogloves [rdplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/centcom_commander": "CentCom commander envirogloves [commanderplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/centcom_official": "CentCom official envirogloves [officialplasma]",
  "/obj/item/clothing/gloves/color/plasmaman/centcom_intern": "CentCom intern envirogloves [internplasma]",
  "/obj/item/clothing/gloves/color/plasmaman": "plasma envirogloves [plasmaman]",
  "/obj/item/clothing/gloves/color": "gloves []",
  "/obj/item/clothing/gloves/cut/heirloom": "fingerless insulated gloves [yellowcut]",
  "/obj/item/clothing/gloves/cut": "fingerless insulated gloves [yellowcut]",
  "/obj/item/clothing/gloves/fingerless": "fingerless gloves [fingerless]",
  "/obj/item/clothing/gloves/combat/wizard": "enchanted gloves [wizard]",
  "/obj/item/clothing/gloves/combat": "combat gloves [black]",
  "/obj/item/clothing/gloves/radio": "translation gloves [radio_g]",
  "/obj/item/clothing/gloves/cargo_gauntlet": "H.A.U.L. gauntlets [haul_gauntlet]",
  "/obj/item/clothing/gloves/rapid": "Gloves of the North Star [rapid]",
  "/obj/item/clothing/gloves/tackler/dolphin": "dolphin gloves [tackledolphin]",
  "/obj/item/clothing/gloves/tackler/combat/insulated": "guerrilla gloves [black]",
  "/obj/item/clothing/gloves/tackler/combat": "gorilla gloves [black]",
  "/obj/item/clothing/gloves/tackler/rocket": "rocket gloves [tacklerocket]",
  "/obj/item/clothing/gloves/tackler/offbrand": "improvised gripper gloves [fingerless]",
  "/obj/item/clothing/gloves/tackler": "gripper gloves [tackle]",
  "/obj/item/clothing/gloves/gauntlets": "concussive gauntlets [concussive_gauntlets]",
  "/obj/item/clothing/gloves/space_ninja": "ninja gloves [black]",
  "/obj/item/clothing/gloves/butchering": "butchering gloves [black]",
  "/obj/item/clothing/gloves": "gloves []"
}
