outfit_options["head"] = {
  "/obj/item/clothing/head/mob_holder/drone": "bugged mob []",
  "/obj/item/clothing/head/mob_holder/destructible": "bugged mob []",
  "/obj/item/clothing/head/mob_holder": "bugged mob []",
  "/obj/item/clothing/head/helmet/chaplain/clock": "forgotten helmet [clockwork_helmet]",
  "/obj/item/clothing/head/helmet/chaplain/cage": "chaplain cage [cage]",
  "/obj/item/clothing/head/helmet/chaplain/ancient": "ancient helmet [knight_ancient]",
  "/obj/item/clothing/head/helmet/chaplain/witchunter_hat": "witchunter hat [witchhunterhat]",
  "/obj/item/clothing/head/helmet/chaplain/adept": "adept hood [crusader]",
  "/obj/item/clothing/head/helmet/chaplain": "crusader helmet [knight_templar]",
  "/obj/item/clothing/head/helmet/plate/crusader/blue": "Crusader's Hood [crusader-blue]",
  "/obj/item/clothing/head/helmet/plate/crusader/red": "Crusader's Hood [crusader-red]",
  "/obj/item/clothing/head/helmet/plate/crusader/prophet/red": "Prophet's Hat [prophet-red]",
  "/obj/item/clothing/head/helmet/plate/crusader/prophet/blue": "Prophet's Hat [prophet-blue]",
  "/obj/item/clothing/head/helmet/plate/crusader/prophet": "Prophet's Hat []",
  "/obj/item/clothing/head/helmet/plate/crusader": "Crusader's Hood [crusader]",
  "/obj/item/clothing/head/helmet/plate": "helmet [plate]",
  "/obj/item/clothing/head/helmet/abductor": "agent headgear [alienhelmet]",
  "/obj/item/clothing/head/helmet/space/changeling": "flesh mass [lingspacehelmet]",
  "/obj/item/clothing/head/helmet/space/hardsuit/cult": "Nar'Sien hardened helmet [cult_helmet]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/light/red": "light shielded hardsuit helmet [hardsuit0-ert_security]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/light/blue": "light shielded hardsuit helmet [hardsuit0-ert_commander]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/light/green": "light shielded hardsuit helmet [hardsuit0-ert_green]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/light/yellow": "light shielded hardsuit helmet [hardsuit0-ert_engineer]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/light": "light shielded hardsuit helmet [hardsuit0-ert_medical]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/red": "shielded hardsuit helmet [hardsuit0-ert_security]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/blue": "shielded hardsuit helmet [hardsuit0-ert_commander]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/green": "shielded hardsuit helmet [hardsuit0-ert_green]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf/yellow": "shielded hardsuit helmet [hardsuit0-ert_engineer]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/ctf": "shielded hardsuit helmet [hardsuit0-ert_medical]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/syndi": "blood-red hardsuit helmet [hardsuit1-syndi]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/swat": "death commando helmet [deathsquad]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded/wizard": "battlemage helmet [battlemage]",
  "/obj/item/clothing/head/helmet/space/hardsuit/shielded": "hardsuit helmet [hardsuit0-engineering]",
  "/obj/item/clothing/head/helmet/space/hardsuit/engine/atmos": "atmospherics hardsuit helmet [hardsuit0-atmospherics]",
  "/obj/item/clothing/head/helmet/space/hardsuit/engine/elite": "advanced hardsuit helmet [hardsuit0-white]",
  "/obj/item/clothing/head/helmet/space/hardsuit/engine": "engineering hardsuit helmet [hardsuit0-engineering]",
  "/obj/item/clothing/head/helmet/space/hardsuit/mining": "mining hardsuit helmet [hardsuit0-mining]",
  "/obj/item/clothing/head/helmet/space/hardsuit/syndi/elite/debug": "elite syndicate hardsuit helmet [hardsuit1-syndielite]",
  "/obj/item/clothing/head/helmet/space/hardsuit/syndi/elite/admin": "jannie hardsuit helmet [hardsuit1-syndielite]",
  "/obj/item/clothing/head/helmet/space/hardsuit/syndi/elite": "elite syndicate hardsuit helmet [hardsuit1-syndielite]",
  "/obj/item/clothing/head/helmet/space/hardsuit/syndi/owl": "owl hardsuit helmet [hardsuit1-owl]",
  "/obj/item/clothing/head/helmet/space/hardsuit/syndi": "blood-red hardsuit helmet [hardsuit1-syndi]",
  "/obj/item/clothing/head/helmet/space/hardsuit/wizard": "gem-encrusted hardsuit helmet [hardsuit0-wiz]",
  "/obj/item/clothing/head/helmet/space/hardsuit/medical": "medical hardsuit helmet [hardsuit0-medical]",
  "/obj/item/clothing/head/helmet/space/hardsuit/rd": "prototype hardsuit helmet [hardsuit0-rd]",
  "/obj/item/clothing/head/helmet/space/hardsuit/security/hos": "head of security's hardsuit helmet [hardsuit0-hos]",
  "/obj/item/clothing/head/helmet/space/hardsuit/security": "security hardsuit helmet [hardsuit0-sec]",
  "/obj/item/clothing/head/helmet/space/hardsuit/swat/captain": "captain's SWAT helmet [capspace]",
  "/obj/item/clothing/head/helmet/space/hardsuit/swat/centcom": "CentCom SWAT helmet [centcomspace]",
  "/obj/item/clothing/head/helmet/space/hardsuit/swat": "MK.II SWAT Helmet [swat2helm]",
  "/obj/item/clothing/head/helmet/space/hardsuit/clown": "cosmohonk hardsuit helmet [hardsuit0-clown]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ancient": "prototype RIG hardsuit helmet [hardsuit0-ancient]",
  "/obj/item/clothing/head/helmet/space/hardsuit/deathsquad": "MK.III SWAT Helmet [deathsquad]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/sec": "emergency response team security helmet [hardsuit0-ert_security]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/engi": "emergency response team engineering helmet [hardsuit0-ert_engineer]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/med": "emergency response team medical helmet [hardsuit0-ert_medical]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/jani": "emergency response team janitorial helmet [hardsuit0-ert_janitor]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/clown": "emergency response team clown helmet [hardsuit0-ert_clown]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/paranormal/inquisitor": "inquisitor's helmet [hardsuit0-inq]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert/paranormal": "paranormal response team helmet [hardsuit0-prt]",
  "/obj/item/clothing/head/helmet/space/hardsuit/ert": "emergency response team commander helmet [hardsuit0-ert_commander]",
  "/obj/item/clothing/head/helmet/space/hardsuit/carp": "carp helmet [carp_helm]",
  "/obj/item/clothing/head/helmet/space/hardsuit/combatmedic": "endemic combat medic helmet [hardsuit0-combatmedic]",
  "/obj/item/clothing/head/helmet/space/hardsuit/hostile_environment": "H.E.C.K. helmet [hardsuit0-heck]",
  "/obj/item/clothing/head/helmet/space/hardsuit/berserker": "berserker helmet [hardsuit0-berserker]",
  "/obj/item/clothing/head/helmet/space/hardsuit/cybersun": "Cybersun hardsuit helmet [cybersun]",
  "/obj/item/clothing/head/helmet/space/hardsuit": "hardsuit helmet [hardsuit0-engineering]",
  "/obj/item/clothing/head/helmet/space/plasmaman/security/warden": "warden's plasma envirosuit helmet [warden_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/security/head_of_security": "head of security's plasma envirosuit helmet [hos_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/security": "security plasma envirosuit helmet [security_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/prisoner": "prisoner's plasma envirosuit helmet [prisoner_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/medical": "medical doctor's plasma envirosuit helmet [doctor_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/paramedic": "paramedic plasma envirosuit helmet [paramedic_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/viro": "virology plasma envirosuit helmet [virologist_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/chemist": "chemistry plasma envirosuit helmet [chemist_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/chief_medical_officer": "chief medical officer's plasma envirosuit helmet [cmo_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/science": "science plasma envirosuit helmet [scientist_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/robotics": "robotics plasma envirosuit helmet [roboticist_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/genetics": "geneticist's plasma envirosuit helmet [geneticist_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/research_director": "research director's plasma envirosuit helmet [rd_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/engineering": "engineering plasma envirosuit helmet [engineer_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/atmospherics": "atmospherics plasma envirosuit helmet [atmos_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/chief_engineer": "chief engineer's plasma envirosuit helmet [ce_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/cargo": "cargo plasma envirosuit helmet [cargo_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/mining": "mining plasma envirosuit helmet [explorer_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/chaplain": "chaplain's plasma envirosuit helmet [chap_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/white": "white plasma envirosuit helmet [white_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/curator": "curator's plasma envirosuit helmet [prototype_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/botany": "botany plasma envirosuit helmet [botany_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/janitor": "janitor's plasma envirosuit helmet [janitor_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/mime": "mime envirosuit helmet [mime_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/clown": "clown envirosuit helmet [clown_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/head_of_personnel": "head of personnel's envirosuit helmet [hop_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/captain": "captain's plasma envirosuit helmet [captain_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/centcom_commander": "CentCom commander plasma envirosuit helmet [commander_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/centcom_official": "CentCom official plasma envirosuit helmet [official_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman/centcom_intern": "CentCom intern plasma envirosuit helmet [intern_envirohelm]",
  "/obj/item/clothing/head/helmet/space/plasmaman": "plasma envirosuit helmet [plasmaman-helm]",
  "/obj/item/clothing/head/helmet/space/chronos": "Chronosuit Helmet [chronohelmet]",
  "/obj/item/clothing/head/helmet/space/freedom": "eagle helmet [griffinhat]",
  "/obj/item/clothing/head/helmet/space/pirate/bandana": "modified EVA helmet [spacebandana]",
  "/obj/item/clothing/head/helmet/space/pirate": "modified EVA helmet [spacepirate]",
  "/obj/item/clothing/head/helmet/space/santahat": "Santa's hat [santahat]",
  "/obj/item/clothing/head/helmet/space/nasavoid/old": "Engineering Void Helmet [void]",
  "/obj/item/clothing/head/helmet/space/nasavoid": "NASA Void Helmet [void]",
  "/obj/item/clothing/head/helmet/space/eva": "EVA helmet [space]",
  "/obj/item/clothing/head/helmet/space/fragile": "emergency space helmet [syndicate-helm-orange]",
  "/obj/item/clothing/head/helmet/space/beret": "officer's beret [beret_badge]",
  "/obj/item/clothing/head/helmet/space/syndicate/green/dark": "dark green space helmet [syndicate-helm-green-dark]",
  "/obj/item/clothing/head/helmet/space/syndicate/green": "green space helmet [syndicate-helm-green]",
  "/obj/item/clothing/head/helmet/space/syndicate/orange": "orange space helmet [syndicate-helm-orange]",
  "/obj/item/clothing/head/helmet/space/syndicate/blue": "blue space helmet [syndicate-helm-blue]",
  "/obj/item/clothing/head/helmet/space/syndicate/black/green": "black space helmet [syndicate-helm-black-green]",
  "/obj/item/clothing/head/helmet/space/syndicate/black/blue": "black space helmet [syndicate-helm-black-blue]",
  "/obj/item/clothing/head/helmet/space/syndicate/black/med": "black space helmet [syndicate-helm-black-med]",
  "/obj/item/clothing/head/helmet/space/syndicate/black/orange": "black space helmet [syndicate-helm-black-orange]",
  "/obj/item/clothing/head/helmet/space/syndicate/black/red": "black space helmet [syndicate-helm-black-red]",
  "/obj/item/clothing/head/helmet/space/syndicate/black/engie": "black space helmet [syndicate-helm-black-engie]",
  "/obj/item/clothing/head/helmet/space/syndicate/black": "black space helmet [syndicate-helm-black]",
  "/obj/item/clothing/head/helmet/space/syndicate/contract": "contractor helmet [syndicate-contract-helm]",
  "/obj/item/clothing/head/helmet/space/syndicate": "red space helmet [syndicate]",
  "/obj/item/clothing/head/helmet/space/space_ninja": "ninja hood [s-ninja]",
  "/obj/item/clothing/head/helmet/space/orange": "emergency space helmet [syndicate-helm-orange]",
  "/obj/item/clothing/head/helmet/space": "space helmet [spaceold]",
  "/obj/item/clothing/head/helmet/changeling": "chitinous mass [lingarmorhelmet]",
  "/obj/item/clothing/head/helmet/sec": "helmet [helmet]",
  "/obj/item/clothing/head/helmet/alt": "bulletproof helmet [helmetalt]",
  "/obj/item/clothing/head/helmet/marine/security": "marine heavy helmet [marine_security]",
  "/obj/item/clothing/head/helmet/marine/engineer": "marine utility helmet [marine_engineer]",
  "/obj/item/clothing/head/helmet/marine/medic": "marine medic helmet [marine_medic]",
  "/obj/item/clothing/head/helmet/marine": "marine combat helmet [marine_command]",
  "/obj/item/clothing/head/helmet/old": "degrading helmet [helmet]",
  "/obj/item/clothing/head/helmet/blueshirt": "blue helmet [blueshift]",
  "/obj/item/clothing/head/helmet/riot": "riot helmet [riot]",
  "/obj/item/clothing/head/helmet/justice/escape": "alarm helmet [justice2]",
  "/obj/item/clothing/head/helmet/justice": "helmet of justice [justice]",
  "/obj/item/clothing/head/helmet/swat/nanotrasen": "SWAT helmet [swat]",
  "/obj/item/clothing/head/helmet/swat": "SWAT helmet [swatsyndie]",
  "/obj/item/clothing/head/helmet/police": "police officer's hat [policehelm]",
  "/obj/item/clothing/head/helmet/constable": "constable helmet [constable]",
  "/obj/item/clothing/head/helmet/thunderdome/holosuit": "Thunderdome helmet [thunderdome]",
  "/obj/item/clothing/head/helmet/thunderdome": "Thunderdome helmet [thunderdome]",
  "/obj/item/clothing/head/helmet/roman/fake": "Roman helmet [roman]",
  "/obj/item/clothing/head/helmet/roman/legionnaire/fake": "Roman legionnaire helmet [roman_c]",
  "/obj/item/clothing/head/helmet/roman/legionnaire": "Roman legionnaire helmet [roman_c]",
  "/obj/item/clothing/head/helmet/roman": "Roman helmet [roman]",
  "/obj/item/clothing/head/helmet/gladiator": "gladiator helmet [gladiator]",
  "/obj/item/clothing/head/helmet/redtaghelm": "red laser tag helmet [redtaghelm]",
  "/obj/item/clothing/head/helmet/bluetaghelm": "blue laser tag helmet [bluetaghelm]",
  "/obj/item/clothing/head/helmet/knight/blue": "medieval helmet [knight_blue]",
  "/obj/item/clothing/head/helmet/knight/yellow": "medieval helmet [knight_yellow]",
  "/obj/item/clothing/head/helmet/knight/red": "medieval helmet [knight_red]",
  "/obj/item/clothing/head/helmet/knight/greyscale": "knight helmet [knight_greyscale]",
  "/obj/item/clothing/head/helmet/knight": "medieval helmet [knight_green]",
  "/obj/item/clothing/head/helmet/skull": "skull helmet [skull]",
  "/obj/item/clothing/head/helmet/durathread": "durathread helmet [durathread]",
  "/obj/item/clothing/head/helmet/rus_helmet": "russian helmet [rus_helmet]",
  "/obj/item/clothing/head/helmet/rus_ushanka": "battle ushanka [rus_ushanka]",
  "/obj/item/clothing/head/helmet/infiltrator": "infiltrator helmet [infiltrator]",
  "/obj/item/clothing/head/helmet/elder_atmosian": "Elder Atmosian Helmet [h2helmet]",
  "/obj/item/clothing/head/helmet/monkey_sentience": "monkey mind magnification helmet [monkeymind]",
  "/obj/item/clothing/head/helmet": "helmet [helmet]",
  "/obj/item/clothing/head/hooded/chaplain_hood/leader": "leader hood [chaplain_hood_leader]",
  "/obj/item/clothing/head/hooded/chaplain_hood": "follower hood [chaplain_hood]",
  "/obj/item/clothing/head/hooded/cult_hoodie/alt": "cultist hood [cult_hoodalt]",
  "/obj/item/clothing/head/hooded/cult_hoodie/cult_shield": "empowered cultist helmet [cult_hoodalt]",
  "/obj/item/clothing/head/hooded/cult_hoodie/berserkerhood": "flagellant's hood [culthood]",
  "/obj/item/clothing/head/hooded/cult_hoodie/eldritch": "ominous hood [eldritch]",
  "/obj/item/clothing/head/hooded/cult_hoodie/void": "void hood [void_cloak]",
  "/obj/item/clothing/head/hooded/cult_hoodie": "ancient cultist hood [culthood]",
  "/obj/item/clothing/head/hooded/ablative": "ablative hood [ablativehood]",
  "/obj/item/clothing/head/hooded/monkhabit": "monk's hood [monkhood]",
  "/obj/item/clothing/head/hooded/cloakhood/goliath": "goliath cloak hood [golhood]",
  "/obj/item/clothing/head/hooded/cloakhood/drake": "drake helm [dragon]",
  "/obj/item/clothing/head/hooded/cloakhood/godslayer": "godslayer helm [godslayer]",
  "/obj/item/clothing/head/hooded/cloakhood": "head [tophat]",
  "/obj/item/clothing/head/hooded/flashsuit": "flash button [flashsuit]",
  "/obj/item/clothing/head/hooded/carp_hood": "carp hood [carp_casual]",
  "/obj/item/clothing/head/hooded/ian_hood": "corgi hood [ian]",
  "/obj/item/clothing/head/hooded/bee_hood": "bee hood [bee]",
  "/obj/item/clothing/head/hooded/human_head": "bloated human head [lingspacehelmet]",
  "/obj/item/clothing/head/hooded/mysticrobe": "mystic's hood [mystichood]",
  "/obj/item/clothing/head/hooded/techpriest": "techpriest's hood [techpriesthood]",
  "/obj/item/clothing/head/hooded/winterhood/centcom": "winter hood [hood_centcom]",
  "/obj/item/clothing/head/hooded/winterhood/captain": "winter hood [hood_captain]",
  "/obj/item/clothing/head/hooded/winterhood/hop": "winter hood [hood_hop]",
  "/obj/item/clothing/head/hooded/winterhood/hydro": "winter hood [hood_hydro]",
  "/obj/item/clothing/head/hooded/winterhood/janitor": "winter hood [hood_janitor]",
  "/obj/item/clothing/head/hooded/winterhood/security/hos": "winter hood [hood_hos]",
  "/obj/item/clothing/head/hooded/winterhood/security": "winter hood [hood_security]",
  "/obj/item/clothing/head/hooded/winterhood/medical/cmo": "winter hood [hood_cmo]",
  "/obj/item/clothing/head/hooded/winterhood/medical/chemistry": "winter hood [hood_chemistry]",
  "/obj/item/clothing/head/hooded/winterhood/medical/viro": "winter hood [hood_viro]",
  "/obj/item/clothing/head/hooded/winterhood/medical/paramedic": "winter hood [hood_paramed]",
  "/obj/item/clothing/head/hooded/winterhood/medical": "winter hood [hood_medical]",
  "/obj/item/clothing/head/hooded/winterhood/science/rd": "winter hood [hood_rd]",
  "/obj/item/clothing/head/hooded/winterhood/science/robotics": "winter hood [hood_robotics]",
  "/obj/item/clothing/head/hooded/winterhood/science/genetics": "winter hood [hood_genetics]",
  "/obj/item/clothing/head/hooded/winterhood/science": "winter hood [hood_science]",
  "/obj/item/clothing/head/hooded/winterhood/engineering/ce": "winter hood [hood_ce]",
  "/obj/item/clothing/head/hooded/winterhood/engineering/atmos": "winter hood [hood_atmos]",
  "/obj/item/clothing/head/hooded/winterhood/engineering": "winter hood [hood_engineer]",
  "/obj/item/clothing/head/hooded/winterhood/cargo": "winter hood [hood_cargo]",
  "/obj/item/clothing/head/hooded/winterhood/qm": "winter hood [hood_qm]",
  "/obj/item/clothing/head/hooded/winterhood/miner": "winter hood [hood_miner]",
  "/obj/item/clothing/head/hooded/winterhood/custom": "tailored winter coat hood [hood_winter]",
  "/obj/item/clothing/head/hooded/winterhood": "winter hood [hood_winter]",
  "/obj/item/clothing/head/hooded/explorer": "explorer hood [explorer]",
  "/obj/item/clothing/head/hooded": "head []",
  "/obj/item/clothing/head/changeling": "flesh []",
  "/obj/item/clothing/head/magus": "magus helm [magus]",
  "/obj/item/clothing/head/chameleon/broken": "grey cap [chameleon_broken]",
  "/obj/item/clothing/head/chameleon/drone": "grey cap [chameleon_drone]",
  "/obj/item/clothing/head/chameleon": "grey cap [chameleon]",
  "/obj/item/clothing/head/kitty/genuine": "kitty ears [kitty_genuine]",
  "/obj/item/clothing/head/kitty": "kitty ears [kitty]",
  "/obj/item/clothing/head/rabbitears": "rabbit ears [bunny]",
  "/obj/item/clothing/head/beanie/black": "black beanie [beanie]",
  "/obj/item/clothing/head/beanie/red": "red beanie [beanie]",
  "/obj/item/clothing/head/beanie/green": "green beanie [beanie]",
  "/obj/item/clothing/head/beanie/darkblue": "dark blue beanie [beanie]",
  "/obj/item/clothing/head/beanie/purple": "purple beanie [beanie]",
  "/obj/item/clothing/head/beanie/yellow": "yellow beanie [beanie]",
  "/obj/item/clothing/head/beanie/orange": "orange beanie [beanie]",
  "/obj/item/clothing/head/beanie/cyan": "cyan beanie [beanie]",
  "/obj/item/clothing/head/beanie/christmas": "christmas beanie [beaniechristmas]",
  "/obj/item/clothing/head/beanie/striped": "striped beanie [beaniestriped]",
  "/obj/item/clothing/head/beanie/stripedred": "red striped beanie [beaniestripedred]",
  "/obj/item/clothing/head/beanie/stripedblue": "blue striped beanie [beaniestripedblue]",
  "/obj/item/clothing/head/beanie/stripedgreen": "green striped beanie [beaniestripedgreen]",
  "/obj/item/clothing/head/beanie/durathread": "durathread beanie [beaniedurathread]",
  "/obj/item/clothing/head/beanie/waldo": "red striped bobble hat [waldo_hat]",
  "/obj/item/clothing/head/beanie/rasta": "rastacap [beanierasta]",
  "/obj/item/clothing/head/beanie": "white beanie [beanie]",
  "/obj/item/clothing/head/hardhat/cakehat/energycake": "energy cake [hardhat0_energycake]",
  "/obj/item/clothing/head/hardhat/cakehat": "cakehat [hardhat0_cakehat]",
  "/obj/item/clothing/head/hardhat/orange": "hard hat [hardhat0_orange]",
  "/obj/item/clothing/head/hardhat/red/upgraded": "workplace-ready firefighter helmet [hardhat0_purple]",
  "/obj/item/clothing/head/hardhat/red": "firefighter helmet [hardhat0_red]",
  "/obj/item/clothing/head/hardhat/white": "hard hat [hardhat0_white]",
  "/obj/item/clothing/head/hardhat/dblue": "hard hat [hardhat0_dblue]",
  "/obj/item/clothing/head/hardhat/atmos": "atmospheric technician's firefighting helmet [hardhat0_atmos]",
  "/obj/item/clothing/head/hardhat/weldhat/orange": "welding hard hat [hardhat0_orange]",
  "/obj/item/clothing/head/hardhat/weldhat/white": "welding hard hat [hardhat0_white]",
  "/obj/item/clothing/head/hardhat/weldhat/dblue": "welding hard hat [hardhat0_dblue]",
  "/obj/item/clothing/head/hardhat/weldhat": "welding hard hat [hardhat0_yellow]",
  "/obj/item/clothing/head/hardhat/pumpkinhead/blumpkin": "carved blumpkin [hardhat0_blumpkin]",
  "/obj/item/clothing/head/hardhat/pumpkinhead": "carved pumpkin [hardhat0_pumpkin]",
  "/obj/item/clothing/head/hardhat/reindeer": "novelty reindeer hat [hardhat0_reindeer]",
  "/obj/item/clothing/head/hardhat": "hard hat [hardhat0_yellow]",
  "/obj/item/clothing/head/collectable/petehat": "ultra rare Pete's hat! [petehat]",
  "/obj/item/clothing/head/collectable/xenom": "collectable xenomorph helmet! [xenom]",
  "/obj/item/clothing/head/collectable/chef": "collectable chef's hat [chef]",
  "/obj/item/clothing/head/collectable/paper": "collectable paper hat [paper]",
  "/obj/item/clothing/head/collectable/tophat": "collectable top hat [tophat]",
  "/obj/item/clothing/head/collectable/captain": "collectable captain's hat [captain]",
  "/obj/item/clothing/head/collectable/police": "collectable police officer's hat [policehelm]",
  "/obj/item/clothing/head/collectable/beret": "collectable beret [beret]",
  "/obj/item/clothing/head/collectable/welding": "collectable welding helmet [welding]",
  "/obj/item/clothing/head/collectable/slime": "collectable slime hat [headslime]",
  "/obj/item/clothing/head/collectable/flatcap": "collectable flat cap [beret_flat]",
  "/obj/item/clothing/head/collectable/pirate": "collectable pirate hat [pirate]",
  "/obj/item/clothing/head/collectable/kitty": "collectable kitty ears [kitty]",
  "/obj/item/clothing/head/collectable/rabbitears": "collectable rabbit ears [bunny]",
  "/obj/item/clothing/head/collectable/wizard": "collectable wizard's hat [wizard]",
  "/obj/item/clothing/head/collectable/hardhat": "collectable hard hat [hardhat0_yellow]",
  "/obj/item/clothing/head/collectable/hos": "collectable HoS hat [hoscap]",
  "/obj/item/clothing/head/collectable/hop": "collectable HoP hat [hopcap]",
  "/obj/item/clothing/head/collectable/thunderdome": "collectable Thunderdome helmet [thunderdome]",
  "/obj/item/clothing/head/collectable/swat": "collectable SWAT helmet [swat]",
  "/obj/item/clothing/head/collectable": "collectable hat []",
  "/obj/item/clothing/head/cone": "warning cone [cone]",
  "/obj/item/clothing/head/powdered_wig": "powdered wig [pwig]",
  "/obj/item/clothing/head/hasturhood": "hastur's hood [hasturhood]",
  "/obj/item/clothing/head/syndicatefake": "black space-helmet replica [syndicate-helm-black-red]",
  "/obj/item/clothing/head/cueball": "cueball helmet [cueball]",
  "/obj/item/clothing/head/snowman": "snowman head [snowman_h]",
  "/obj/item/clothing/head/witchwig": "witch costume wig [witch]",
  "/obj/item/clothing/head/chicken": "chicken suit head [chickenhead]",
  "/obj/item/clothing/head/griffin": "griffon head [griffinhat]",
  "/obj/item/clothing/head/xenos": "xenos helmet [xenos]",
  "/obj/item/clothing/head/lobsterhat": "foam lobster head [lobster_hat]",
  "/obj/item/clothing/head/drfreezehat": "doctor freeze's wig [drfreeze_hat]",
  "/obj/item/clothing/head/shrine_wig": "shrine maiden's wig [shrine_wig]",
  "/obj/item/clothing/head/cardborg": "cardborg helmet [cardborg_h]",
  "/obj/item/clothing/head/bronze": "bronze hat [clockwork_helmet_old]",
  "/obj/item/clothing/head/crown/fancy": "magnificent crown [fancycrown]",
  "/obj/item/clothing/head/crown": "crown [crown]",
  "/obj/item/clothing/head/fedora/white": "white fedora [fedora_white]",
  "/obj/item/clothing/head/fedora/beige": "beige fedora [fedora_beige]",
  "/obj/item/clothing/head/fedora/det_hat": "detective's fedora [detective]",
  "/obj/item/clothing/head/fedora/curator": "treasure hunter's fedora [curator]",
  "/obj/item/clothing/head/fedora": "fedora [fedora]",
  "/obj/item/clothing/head/frenchberet": "french beret [beret]",
  "/obj/item/clothing/head/centhat": "CentCom hat [centcom]",
  "/obj/item/clothing/head/spacepolice": "space police cap [policecap_families]",
  "/obj/item/clothing/head/canada": "striped red tophat [canada]",
  "/obj/item/clothing/head/redcoat": "redcoat's hat [redcoat]",
  "/obj/item/clothing/head/mailman": "mailman's hat [mailman]",
  "/obj/item/clothing/head/plaguedoctorhat": "plague doctor's hat [plaguedoctor]",
  "/obj/item/clothing/head/nursehat": "nurse's hat [nursehat]",
  "/obj/item/clothing/head/bowler": "bowler-hat [bowler]",
  "/obj/item/clothing/head/bearpelt": "bear pelt hat [bearpelt]",
  "/obj/item/clothing/head/flatcap": "flat cap [beret_flat]",
  "/obj/item/clothing/head/hunter": "bounty hunting hat [cowboy]",
  "/obj/item/clothing/head/santa": "santa hat [santahatnorm]",
  "/obj/item/clothing/head/jester/alt": "jester hat [jester2]",
  "/obj/item/clothing/head/jester": "jester hat [jester_hat]",
  "/obj/item/clothing/head/rice_hat": "rice hat [rice_hat]",
  "/obj/item/clothing/head/lizard": "lizardskin cloche hat [lizard]",
  "/obj/item/clothing/head/scarecrow_hat": "scarecrow hat [scarecrow_hat]",
  "/obj/item/clothing/head/pharaoh": "pharaoh hat [pharoah_hat]",
  "/obj/item/clothing/head/nemes": "headdress of Nemes [nemes_headdress]",
  "/obj/item/clothing/head/delinquent": "delinquent hat [delinquent]",
  "/obj/item/clothing/head/intern": "CentCom Head Intern beancap [intern_hat]",
  "/obj/item/clothing/head/coordinator": "coordinator cap [capcap]",
  "/obj/item/clothing/head/jackbros": "frosty hat [JackFrostHat]",
  "/obj/item/clothing/head/weddingveil": "wedding veil [weddingveil]",
  "/obj/item/clothing/head/centcom_cap": "CentCom commander cap [centcom_cap]",
  "/obj/item/clothing/head/human_leather": "human skin hat [human_leather]",
  "/obj/item/clothing/head/ushanka": "ushanka [ushankadown]",
  "/obj/item/clothing/head/chefhat/i_am_assuming_direct_control": "chef's hat [direct_control]",
  "/obj/item/clothing/head/chefhat": "chef's hat [chef]",
  "/obj/item/clothing/head/caphat/parade": "captain's parade cap [capcap]",
  "/obj/item/clothing/head/caphat/beret": "captain's beret [beret_badge]",
  "/obj/item/clothing/head/caphat": "captain's hat [captain]",
  "/obj/item/clothing/head/hopcap": "head of personnel's cap [hopcap]",
  "/obj/item/clothing/head/nun_hood": "nun hood [nun_hood]",
  "/obj/item/clothing/head/bishopmitre": "bishop mitre [bishopmitre]",
  "/obj/item/clothing/head/beret/sec/navywarden": "warden's beret [beret_badge]",
  "/obj/item/clothing/head/beret/sec/navyofficer": "security beret [beret_badge]",
  "/obj/item/clothing/head/beret/sec": "security beret [beret_badge]",
  "/obj/item/clothing/head/beret/science/fancy": "science beret [beret_badge]",
  "/obj/item/clothing/head/beret/science": "science beret [beret]",
  "/obj/item/clothing/head/beret/medical/paramedic": "paramedic beret [beret]",
  "/obj/item/clothing/head/beret/medical": "medical beret [beret]",
  "/obj/item/clothing/head/beret/engi": "engineering beret [beret]",
  "/obj/item/clothing/head/beret/atmos": "atmospheric beret [beret]",
  "/obj/item/clothing/head/beret/cargo": "cargo beret [beret]",
  "/obj/item/clothing/head/beret/black": "black beret [beret]",
  "/obj/item/clothing/head/beret/durathread": "durathread beret [beret_badge]",
  "/obj/item/clothing/head/beret/highlander": "beret [beret]",
  "/obj/item/clothing/head/beret/centcom_formal": "CentCom Formal Beret [beret_badge]",
  "/obj/item/clothing/head/beret": "beret [beret]",
  "/obj/item/clothing/head/hos/syndicate": "syndicate cap [hoscap]",
  "/obj/item/clothing/head/hos/beret/navyhos": "head of security's beret [beret_badge]",
  "/obj/item/clothing/head/hos/beret/syndicate": "syndicate beret [beret_badge]",
  "/obj/item/clothing/head/hos/beret": "head of security beret [beret_badge]",
  "/obj/item/clothing/head/hos": "head of security cap [hoscap]",
  "/obj/item/clothing/head/warden/drill": "warden's campaign hat [wardendrill]",
  "/obj/item/clothing/head/warden": "warden's police hat [policehelm]",
  "/obj/item/clothing/head/justice/blue": "justice hat [justiceblue]",
  "/obj/item/clothing/head/justice/yellow": "justice hat [justiceyellow]",
  "/obj/item/clothing/head/justice/green": "justice hat [justicegreen]",
  "/obj/item/clothing/head/justice/pink": "justice hat [justicepink]",
  "/obj/item/clothing/head/justice": "justice hat [justicered]",
  "/obj/item/clothing/head/papersack/smiley": "paper sack hat [papersack_smile]",
  "/obj/item/clothing/head/papersack": "paper sack hat [papersack]",
  "/obj/item/clothing/head/pirate/armored": "pirate hat [pirate]",
  "/obj/item/clothing/head/pirate/captain": "pirate captain hat [hgpiratecap]",
  "/obj/item/clothing/head/pirate": "pirate hat [pirate]",
  "/obj/item/clothing/head/bandana/armored": "pirate bandana [bandana]",
  "/obj/item/clothing/head/bandana": "pirate bandana [bandana]",
  "/obj/item/clothing/head/clownmitre": "Hat of the Honkmother [clownmitre]",
  "/obj/item/clothing/head/kippah": "kippah [kippah]",
  "/obj/item/clothing/head/medievaljewhat": "medieval Jewish hat [medievaljewhat]",
  "/obj/item/clothing/head/taqiyahwhite": "white taqiyah [taqiyahwhite]",
  "/obj/item/clothing/head/taqiyahred": "red taqiyah [taqiyahred]",
  "/obj/item/clothing/head/soft/red": "red cap [redsoft]",
  "/obj/item/clothing/head/soft/blue": "blue cap [bluesoft]",
  "/obj/item/clothing/head/soft/green": "green cap [greensoft]",
  "/obj/item/clothing/head/soft/yellow": "yellow cap [yellowsoft]",
  "/obj/item/clothing/head/soft/grey/jolly": "jolly grey cap [greysoft]",
  "/obj/item/clothing/head/soft/grey": "grey cap [greysoft]",
  "/obj/item/clothing/head/soft/orange": "orange cap [orangesoft]",
  "/obj/item/clothing/head/soft/mime": "white cap [mimesoft]",
  "/obj/item/clothing/head/soft/purple": "purple cap [purplesoft]",
  "/obj/item/clothing/head/soft/black": "black cap [blacksoft]",
  "/obj/item/clothing/head/soft/rainbow": "rainbow cap [rainbowsoft]",
  "/obj/item/clothing/head/soft/sec": "security cap [secsoft]",
  "/obj/item/clothing/head/soft/paramedic": "paramedic cap [paramedicsoft]",
  "/obj/item/clothing/head/soft": "cargo cap [cargosoft]",
  "/obj/item/clothing/head/sombrero/green": "green sombrero [sombrero]",
  "/obj/item/clothing/head/sombrero/shamebrero": "shamebrero [shamebrero]",
  "/obj/item/clothing/head/sombrero": "sombrero [sombrero]",
  "/obj/item/clothing/head/foilhat": "tinfoil hat [foilhat]",
  "/obj/item/clothing/head/that": "top-hat [tophat]",
  "/obj/item/clothing/head/welding": "welding helmet [welding]",
  "/obj/item/clothing/head/wig/random": "wig [hair_vlong]",
  "/obj/item/clothing/head/wig/natural": "natural wig [hair_vlong]",
  "/obj/item/clothing/head/wig": "wig [hair_vlong]",
  "/obj/item/clothing/head/bio_hood/general": "bio hood [bio_general]",
  "/obj/item/clothing/head/bio_hood/virology": "bio hood [bio_virology]",
  "/obj/item/clothing/head/bio_hood/security": "bio hood [bio_security]",
  "/obj/item/clothing/head/bio_hood/janitor": "bio hood [bio_janitor]",
  "/obj/item/clothing/head/bio_hood/scientist": "bio hood [bio_scientist]",
  "/obj/item/clothing/head/bio_hood/cmo": "bio hood [bio_cmo]",
  "/obj/item/clothing/head/bio_hood": "bio hood [bio]",
  "/obj/item/clothing/head/bomb_hood/security": "bomb hood [bombsuit_sec]",
  "/obj/item/clothing/head/bomb_hood/white": "bomb hood [bombsuit_white]",
  "/obj/item/clothing/head/bomb_hood": "bomb hood [bombsuit]",
  "/obj/item/clothing/head/radiation": "radiation hood [rad]",
  "/obj/item/clothing/head/wizard/red": "red wizard hat [redwizard]",
  "/obj/item/clothing/head/wizard/yellow": "yellow wizard hat [yellowwizard]",
  "/obj/item/clothing/head/wizard/black": "black wizard hat [blackwizard]",
  "/obj/item/clothing/head/wizard/fake": "wizard hat [wizard-fake]",
  "/obj/item/clothing/head/wizard/marisa/fake": "witch hat [marisa-fake]",
  "/obj/item/clothing/head/wizard/marisa": "witch hat [marisa]",
  "/obj/item/clothing/head/wizard/magus": "Magus helm [magus]",
  "/obj/item/clothing/head/wizard/santa": "Santa's hat [santahat]",
  "/obj/item/clothing/head/wizard": "wizard hat [wizard]",
  "/obj/item/clothing/head/festive": "festive paper hat [xmashat]",
  "/obj/item/clothing/head/bunnyhead": "Easter Bunny Head [bunnyhead]",
  "/obj/item/clothing/head/beekeeper_head": "beekeeper hat [beekeeper]",
  "/obj/item/clothing/head/peaceflower": "heroine bud [peaceflower]",
  "/obj/item/clothing/head": "head []"
}
