outfit_options["mask"] = {
  "/obj/item/clothing/mask/cigarette/space_cigarette": "cigarette [space_cigarette]",
  "/obj/item/clothing/mask/cigarette/dromedary": "cigarette [dromedary]",
  "/obj/item/clothing/mask/cigarette/uplift": "cigarette [uplift]",
  "/obj/item/clothing/mask/cigarette/robust": "cigarette [robust]",
  "/obj/item/clothing/mask/cigarette/robustgold": "cigarette [robustgold]",
  "/obj/item/clothing/mask/cigarette/carp": "cigarette [carp]",
  "/obj/item/clothing/mask/cigarette/syndicate": "cigarette [syndicate]",
  "/obj/item/clothing/mask/cigarette/shadyjims": "cigarette [shadyjims]",
  "/obj/item/clothing/mask/cigarette/xeno": "cigarette [xeno]",
  "/obj/item/clothing/mask/cigarette/rollie/nicotine": "rollie [nicotine]",
  "/obj/item/clothing/mask/cigarette/rollie/trippy": "rollie [trippy]",
  "/obj/item/clothing/mask/cigarette/rollie/cannabis": "rollie [cannabis]",
  "/obj/item/clothing/mask/cigarette/rollie/mindbreaker": "rollie [mindbreaker]",
  "/obj/item/clothing/mask/cigarette/rollie": "rollie [rollie]",
  "/obj/item/clothing/mask/cigarette/candy/nicotine": "Little Timmy's candy cigarette [nicotine]",
  "/obj/item/clothing/mask/cigarette/candy": "Little Timmy's candy cigarette [candy]",
  "/obj/item/clothing/mask/cigarette/cigar/cohiba": "Cohiba Robusto cigar [cohiba]",
  "/obj/item/clothing/mask/cigarette/cigar/havana": "premium Havanian cigar [havana]",
  "/obj/item/clothing/mask/cigarette/cigar": "premium cigar [cigar]",
  "/obj/item/clothing/mask/cigarette/pipe/cobpipe": "corn cob pipe [cobpipe]",
  "/obj/item/clothing/mask/cigarette/pipe": "smoking pipe [pipe]",
  "/obj/item/clothing/mask/cigarette": "cigarette [cigarette]",
  "/obj/item/clothing/mask/vape": "E-Cigarette [red_vape]",
  "/obj/item/clothing/mask/changeling": "flesh []",
  "/obj/item/clothing/mask/fakemoustache/sticky": "fake moustache [fake-moustache]",
  "/obj/item/clothing/mask/fakemoustache/italian": "italian moustache [fake-moustache]",
  "/obj/item/clothing/mask/fakemoustache": "fake moustache [fake-moustache]",
  "/obj/item/clothing/mask/void_mask": "Abyssal Mask [mad_mask]",
  "/obj/item/clothing/mask/chameleon/broken": "gas mask [chameleon_broken]",
  "/obj/item/clothing/mask/chameleon/drone": "gas mask [chameleon_drone]",
  "/obj/item/clothing/mask/chameleon/gps": "gas mask [chameleon_gps]",
  "/obj/item/clothing/mask/chameleon": "gas mask [chameleon]",
  "/obj/item/clothing/mask/animal/pig/cursed": "pig mask [pig_cursed]",
  "/obj/item/clothing/mask/animal/pig": "pig mask [pig]",
  "/obj/item/clothing/mask/animal/frog/cursed": "frog mask [frog_cursed]",
  "/obj/item/clothing/mask/animal/frog": "frog mask [frog]",
  "/obj/item/clothing/mask/animal/cowmask/cursed": "cow mask [cowmask_cursed]",
  "/obj/item/clothing/mask/animal/cowmask": "cow mask [cowmask]",
  "/obj/item/clothing/mask/animal/horsehead/cursed": "horse mask [horsehead_cursed]",
  "/obj/item/clothing/mask/animal/horsehead": "horse mask [horsehead]",
  "/obj/item/clothing/mask/animal/rat/cursed": "rat mask [rat_cursed]",
  "/obj/item/clothing/mask/animal/rat/fox/cursed": "fox mask [fox_cursed]",
  "/obj/item/clothing/mask/animal/rat/fox": "fox mask [fox]",
  "/obj/item/clothing/mask/animal/rat/bee/cursed": "bee mask [bee_cursed]",
  "/obj/item/clothing/mask/animal/rat/bee": "bee mask [bee]",
  "/obj/item/clothing/mask/animal/rat/bear/cursed": "bear mask [bear_cursed]",
  "/obj/item/clothing/mask/animal/rat/bear": "bear mask [bear]",
  "/obj/item/clothing/mask/animal/rat/bat/cursed": "bat mask [bat_cursed]",
  "/obj/item/clothing/mask/animal/rat/bat": "bat mask [bat]",
  "/obj/item/clothing/mask/animal/rat/raven/cursed": "raven mask [raven_cursed]",
  "/obj/item/clothing/mask/animal/rat/raven": "raven mask [raven]",
  "/obj/item/clothing/mask/animal/rat/jackal/cursed": "jackal mask [jackal_cursed]",
  "/obj/item/clothing/mask/animal/rat/jackal": "jackal mask [jackal]",
  "/obj/item/clothing/mask/animal/rat/tribal/cursed": "tribal mask [bumba_cursed]",
  "/obj/item/clothing/mask/animal/rat/tribal": "tribal mask [bumba]",
  "/obj/item/clothing/mask/animal/rat": "rat mask [rat]",
  "/obj/item/clothing/mask/animal": "mask []",
  "/obj/item/clothing/mask/bandana/red": "red bandana [bandred]",
  "/obj/item/clothing/mask/bandana/blue": "blue bandana [bandblue]",
  "/obj/item/clothing/mask/bandana/green": "green bandana [bandgreen]",
  "/obj/item/clothing/mask/bandana/gold": "gold bandana [bandgold]",
  "/obj/item/clothing/mask/bandana/black": "black bandana [bandblack]",
  "/obj/item/clothing/mask/bandana/skull": "skull bandana [bandskull]",
  "/obj/item/clothing/mask/bandana/durathread": "durathread bandana [banddurathread]",
  "/obj/item/clothing/mask/bandana": "botany bandana [bandbotany]",
  "/obj/item/clothing/mask/balaclava": "balaclava [balaclava]",
  "/obj/item/clothing/mask/infiltrator": "infiltrator balaclava [syndicate_balaclava]",
  "/obj/item/clothing/mask/luchador/tecnicos": "Tecnicos Mask [luchador]",
  "/obj/item/clothing/mask/luchador/rudos": "Rudos Mask [luchar]",
  "/obj/item/clothing/mask/luchador": "Luchador Mask [luchag]",
  "/obj/item/clothing/mask/russian_balaclava": "russian balaclava [rus_balaclava]",
  "/obj/item/clothing/mask/breath/medical": "medical mask [medical]",
  "/obj/item/clothing/mask/breath": "breath mask [breath]",
  "/obj/item/clothing/mask/joy": "joy mask [joy]",
  "/obj/item/clothing/mask/mummy": "mummy mask [mummy_mask]",
  "/obj/item/clothing/mask/scarecrow": "sack mask [scarecrow_sack]",
  "/obj/item/clothing/mask/gas/atmos/captain": "captain's gas mask [gas_cap]",
  "/obj/item/clothing/mask/gas/atmos/centcom": "CentCom gas mask [gas_centcom]",
  "/obj/item/clothing/mask/gas/atmos": "atmospheric gas mask [gas_atmos]",
  "/obj/item/clothing/mask/gas/welding/up": "welding mask [weldingmask]",
  "/obj/item/clothing/mask/gas/welding": "welding mask [weldingmask]",
  "/obj/item/clothing/mask/gas/plaguedoctor": "plague doctor mask [plaguedoctor]",
  "/obj/item/clothing/mask/gas/syndicate": "syndicate mask [syndicate]",
  "/obj/item/clothing/mask/gas/clown_hat/plasmaman": "clown wig and mask [clown]",
  "/obj/item/clothing/mask/gas/clown_hat": "clown wig and mask [clown]",
  "/obj/item/clothing/mask/gas/sexyclown": "sexy-clown wig and mask [sexyclown]",
  "/obj/item/clothing/mask/gas/mime/plasmaman": "mime mask [mime_plasmaman]",
  "/obj/item/clothing/mask/gas/mime": "mime mask [mime]",
  "/obj/item/clothing/mask/gas/monkeymask": "monkey mask [monkeymask]",
  "/obj/item/clothing/mask/gas/sexymime": "sexy mime mask [sexymime]",
  "/obj/item/clothing/mask/gas/cyborg": "cyborg visor [death]",
  "/obj/item/clothing/mask/gas/owl_mask": "owl mask [owl]",
  "/obj/item/clothing/mask/gas/carp": "carp mask [carp_mask]",
  "/obj/item/clothing/mask/gas/tiki_mask/yalp_elor": "tiki mask [tiki_yalp]",
  "/obj/item/clothing/mask/gas/tiki_mask": "tiki mask [tiki_eyebrow]",
  "/obj/item/clothing/mask/gas/hunter": "bounty hunting mask [hunter]",
  "/obj/item/clothing/mask/gas/sechailer/swat/spacepol": "spacepol mask [spacepol]",
  "/obj/item/clothing/mask/gas/sechailer/swat": "SWAT mask [swat]",
  "/obj/item/clothing/mask/gas/sechailer/cyborg": "security hailer [taperecorder_idle]",
  "/obj/item/clothing/mask/gas/sechailer": "security gas mask [sechailer]",
  "/obj/item/clothing/mask/gas/explorer/folded": "explorer gas mask [gas_mining]",
  "/obj/item/clothing/mask/gas/explorer": "explorer gas mask [gas_mining]",
  "/obj/item/clothing/mask/gas/space_ninja": "ninja mask [s-ninja]",
  "/obj/item/clothing/mask/gas": "gas mask [gas_alt]",
  "/obj/item/clothing/mask/gondola": "gondola mask [gondola]",
  "/obj/item/clothing/mask/whistle": "police whistle [whistle]",
  "/obj/item/clothing/mask/muzzle/breath": "surgery mask [breathmuzzle]",
  "/obj/item/clothing/mask/muzzle": "muzzle [muzzle]",
  "/obj/item/clothing/mask/surgical": "sterile mask [sterile]",
  "/obj/item/clothing/mask/facehugger/lamarr": "Lamarr [facehugger]",
  "/obj/item/clothing/mask/facehugger/dead": "alien [facehugger_dead]",
  "/obj/item/clothing/mask/facehugger/impregnated": "alien [facehugger_impregnated]",
  "/obj/item/clothing/mask/facehugger/toy": "alien [toy_facehugger]",
  "/obj/item/clothing/mask/facehugger": "alien [facehugger]",
  "/obj/item/clothing/mask/nobreath": "rebreather mask [slime]",
  "/obj/item/clothing/mask": "mask []"
}
