outfit_options["neck"] = {
  "/obj/item/clothing/neck/eldritch_amulet/piercing": "Piercing Eldritch Medallion [eye_medalion]",
  "/obj/item/clothing/neck/eldritch_amulet": "Warm Eldritch Medallion [eye_medalion]",
  "/obj/item/clothing/neck/chameleon/broken": "black tie [chameleon_broken]",
  "/obj/item/clothing/neck/chameleon": "black tie [chameleon]",
  "/obj/item/clothing/neck/tie/blue": "blue tie [bluetie]",
  "/obj/item/clothing/neck/tie/red": "red tie [redtie]",
  "/obj/item/clothing/neck/tie/black": "black tie [blacktie]",
  "/obj/item/clothing/neck/tie/horrible": "horrible tie [horribletie]",
  "/obj/item/clothing/neck/tie/detective": "loose tie [detective]",
  "/obj/item/clothing/neck/tie": "tie []",
  "/obj/item/clothing/neck/stethoscope": "stethoscope [stethoscope]",
  "/obj/item/clothing/neck/scarf/black": "black scarf [scarf]",
  "/obj/item/clothing/neck/scarf/pink": "pink scarf [scarf]",
  "/obj/item/clothing/neck/scarf/red": "red scarf [scarf]",
  "/obj/item/clothing/neck/scarf/green": "green scarf [scarf]",
  "/obj/item/clothing/neck/scarf/darkblue": "dark blue scarf [scarf]",
  "/obj/item/clothing/neck/scarf/purple": "purple scarf [scarf]",
  "/obj/item/clothing/neck/scarf/yellow": "yellow scarf [scarf]",
  "/obj/item/clothing/neck/scarf/orange": "orange scarf [scarf]",
  "/obj/item/clothing/neck/scarf/cyan": "cyan scarf [scarf]",
  "/obj/item/clothing/neck/scarf/zebra": "zebra scarf [zebrascarf]",
  "/obj/item/clothing/neck/scarf/christmas": "christmas scarf [christmasscarf]",
  "/obj/item/clothing/neck/scarf": "white scarf [scarf]",
  "/obj/item/clothing/neck/stripedredscarf": "striped red scarf [stripedredscarf]",
  "/obj/item/clothing/neck/stripedgreenscarf": "striped green scarf [stripedgreenscarf]",
  "/obj/item/clothing/neck/stripedbluescarf": "striped blue scarf [stripedbluescarf]",
  "/obj/item/clothing/neck/petcollar": "pet collar [petcollar]",
  "/obj/item/clothing/neck/necklace/dope/merchant": "gold necklace [merchant]",
  "/obj/item/clothing/neck/necklace/dope": "gold necklace [bling]",
  "/obj/item/clothing/neck/necklace/memento_mori": "Memento Mori [memento_mori]",
  "/obj/item/clothing/neck/necklace": "necklace []",
  "/obj/item/clothing/neck/neckerchief": "necklace []",
  "/obj/item/clothing/neck/beads": "plastic bead necklace [beads]",
  "/obj/item/clothing/neck/cloak/hos": "head of security's cloak [hoscloak]",
  "/obj/item/clothing/neck/cloak/qm": "quartermaster's cloak [qmcloak]",
  "/obj/item/clothing/neck/cloak/cmo": "chief medical officer's cloak [cmocloak]",
  "/obj/item/clothing/neck/cloak/ce": "chief engineer's cloak [cecloak]",
  "/obj/item/clothing/neck/cloak/rd": "research director's cloak [rdcloak]",
  "/obj/item/clothing/neck/cloak/cap": "captain's cloak [capcloak]",
  "/obj/item/clothing/neck/cloak/hop": "head of personnel's cloak [hopcloak]",
  "/obj/item/clothing/neck/cloak/skill_reward/gaming": "legendary gamer's cloak [gamercloak]",
  "/obj/item/clothing/neck/cloak/skill_reward/cleaning": "legendary cleaner's cloak [cleanercloak]",
  "/obj/item/clothing/neck/cloak/skill_reward/mining": "legendary miner's cloak [minercloak]",
  "/obj/item/clothing/neck/cloak/skill_reward/playing": "legendary veteran's cloak [playercloak]",
  "/obj/item/clothing/neck/cloak/skill_reward": "brown cloak [qmcloak]",
  "/obj/item/clothing/neck/cloak/herald_cloak": "cloak of the prophet [herald_cloak]",
  "/obj/item/clothing/neck/cloak": "brown cloak [qmcloak]",
  "/obj/item/clothing/neck": "necklace []"
}
