outfit_options["shoes"] = {
  "/obj/item/clothing/shoes/sneakers/black": "black shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/brown": "brown shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/blue": "blue shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/green": "green shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/yellow": "yellow shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/purple": "purple shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/red": "red shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/white": "white shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/rainbow": "rainbow shoes [rain_bow]",
  "/obj/item/clothing/shoes/sneakers/orange": "orange shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/mime": "mime shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/marisa": "magic shoes [sneakers]",
  "/obj/item/clothing/shoes/sneakers/cyborg": "cyborg boots [sneakers]",
  "/obj/item/clothing/shoes/sneakers": "shoes [sneakers]",
  "/obj/item/clothing/shoes/plate/red": "Plate Boots [crusader-red]",
  "/obj/item/clothing/shoes/plate/blue": "Plate Boots [crusader-blue]",
  "/obj/item/clothing/shoes/plate": "Plate Boots [crusader]",
  "/obj/item/clothing/shoes/changeling": "flesh []",
  "/obj/item/clothing/shoes/clown_shoes/combat": "combat clown shoes [clown]",
  "/obj/item/clothing/shoes/clown_shoes/banana_shoes/combat": "mk-honk combat shoes [clown_prototype_off]",
  "/obj/item/clothing/shoes/clown_shoes/banana_shoes": "mk-honk prototype shoes [clown_prototype_off]",
  "/obj/item/clothing/shoes/clown_shoes/jester": "jester shoes [jester_shoes]",
  "/obj/item/clothing/shoes/clown_shoes": "clown shoes [clown]",
  "/obj/item/clothing/shoes/combat/coldres": "insulated combat boots [jackboots]",
  "/obj/item/clothing/shoes/combat/sneakboots": "sneakboots [sneakboots]",
  "/obj/item/clothing/shoes/combat/swat": "SWAT boots [jackboots]",
  "/obj/item/clothing/shoes/combat": "combat boots [jackboots]",
  "/obj/item/clothing/shoes/chameleon/noslip/broken": "black shoes [chameleon_noslip_broken]",
  "/obj/item/clothing/shoes/chameleon/noslip": "black shoes [chameleon_noslip]",
  "/obj/item/clothing/shoes/chameleon": "black shoes [chameleon]",
  "/obj/item/clothing/shoes/jackboots/fast": "jackboots [fast_jackboots]",
  "/obj/item/clothing/shoes/jackboots": "jackboots [jackboots]",
  "/obj/item/clothing/shoes/winterboots/ice_boots/ice_trail": "cursed ice hiking boots [iceboots]",
  "/obj/item/clothing/shoes/winterboots/ice_boots": "ice hiking boots [iceboots]",
  "/obj/item/clothing/shoes/winterboots": "winter boots [winterboots]",
  "/obj/item/clothing/shoes/workboots/mining": "mining boots [explorer]",
  "/obj/item/clothing/shoes/workboots": "work boots [workboots]",
  "/obj/item/clothing/shoes/russian": "russian boots [rus_shoes]",
  "/obj/item/clothing/shoes/roman": "roman sandals [roman]",
  "/obj/item/clothing/shoes/griffin": "griffon boots [griffinboots]",
  "/obj/item/clothing/shoes/singery": "yellow performer's boots [ysing]",
  "/obj/item/clothing/shoes/singerb": "blue performer's boots [bsing]",
  "/obj/item/clothing/shoes/bronze": "bronze boots [clockwork_treads]",
  "/obj/item/clothing/shoes/cookflops": "grilling sandals [cookflops]",
  "/obj/item/clothing/shoes/yakuza": "tojo clan shoes [MajimaShoes]",
  "/obj/item/clothing/shoes/jackbros": "frosty boots [JackFrostShoes]",
  "/obj/item/clothing/shoes/swagshoes": "swag shoes [SwagShoes]",
  "/obj/item/clothing/shoes/cowboy/white": "white cowboy boots [cowboy_white]",
  "/obj/item/clothing/shoes/cowboy/black": "black cowboy boots [cowboy_black]",
  "/obj/item/clothing/shoes/cowboy/fancy": "bilton wrangler boots [cowboy_fancy]",
  "/obj/item/clothing/shoes/cowboy/lizard/masterwork": "Hugs-The-Feet lizard skin boots [lizardboots_blue]",
  "/obj/item/clothing/shoes/cowboy/lizard": "lizard skin boots [lizardboots_green]",
  "/obj/item/clothing/shoes/cowboy": "cowboy boots [cowboy_brown]",
  "/obj/item/clothing/shoes/cult/alt/ghost": "cultist boots [cultalt]",
  "/obj/item/clothing/shoes/cult/alt": "cultist boots [cultalt]",
  "/obj/item/clothing/shoes/cult": "Nar'Sien invoker boots [cult]",
  "/obj/item/clothing/shoes/galoshes/dry": "absorbent galoshes [galoshes_dry]",
  "/obj/item/clothing/shoes/galoshes": "galoshes [galoshes]",
  "/obj/item/clothing/shoes/gunboots/disabler": "disaboots [jackboots]",
  "/obj/item/clothing/shoes/gunboots": "gunboots [jackboots]",
  "/obj/item/clothing/shoes/bhop/rocket": "rocket boots [rocketboots]",
  "/obj/item/clothing/shoes/bhop": "jump boots [jetboots]",
  "/obj/item/clothing/shoes/kindle_kicks": "Kindle Kicks [kindleKicks]",
  "/obj/item/clothing/shoes/laceup": "laceup shoes [laceups]",
  "/obj/item/clothing/shoes/magboots/advance": "advanced magboots [advmag0]",
  "/obj/item/clothing/shoes/magboots/syndie": "blood-red magboots [syndiemag0]",
  "/obj/item/clothing/shoes/magboots": "magboots [magboots0]",
  "/obj/item/clothing/shoes/sandal/magic": "magical sandals [wizard]",
  "/obj/item/clothing/shoes/sandal": "sandals [wizard]",
  "/obj/item/clothing/shoes/wheelys/rollerskates": "roller skates [rollerskates]",
  "/obj/item/clothing/shoes/wheelys/skishoes": "ski shoes [skishoes]",
  "/obj/item/clothing/shoes/wheelys": "Wheely-Heels [sneakers]",
  "/obj/item/clothing/shoes/space_ninja": "ninja shoes [s-ninja]",
  "/obj/item/clothing/shoes": "shoes []"
}
