outfit_options["suit"] = {
  "/obj/item/clothing/suit/hooded/ian_costume": "corgi costume [ian]",
  "/obj/item/clothing/suit/hooded/chaplain_hoodie/leader": "leader hoodie [chaplain_hoodie_leader]",
  "/obj/item/clothing/suit/hooded/chaplain_hoodie": "follower hoodie [chaplain_hoodie]",
  "/obj/item/clothing/suit/hooded/cultrobes/alt/ghost": "cultist robes [cultrobesalt]",
  "/obj/item/clothing/suit/hooded/cultrobes/alt": "cultist robes [cultrobesalt]",
  "/obj/item/clothing/suit/hooded/cultrobes/cult_shield": "empowered cultist armor [cult_armor]",
  "/obj/item/clothing/suit/hooded/cultrobes/berserker": "flagellant's robes [cultrobes]",
  "/obj/item/clothing/suit/hooded/cultrobes/eldritch": "ominous armor [eldritch_armor]",
  "/obj/item/clothing/suit/hooded/cultrobes/void": "void cloak [void_cloak]",
  "/obj/item/clothing/suit/hooded/cultrobes": "ancient cultist robes [cultrobes]",
  "/obj/item/clothing/suit/hooded/ablative": "ablative trenchcoat [ablativecoat]",
  "/obj/item/clothing/suit/hooded/chaplainsuit/monkhabit": "monk's habit [monkfrock]",
  "/obj/item/clothing/suit/hooded/chaplainsuit": "suit []",
  "/obj/item/clothing/suit/hooded/cloak/goliath": "goliath cloak [goliath_cloak]",
  "/obj/item/clothing/suit/hooded/cloak/drake": "drake armour [dragon]",
  "/obj/item/clothing/suit/hooded/cloak/godslayer": "godslayer armour [godslayer]",
  "/obj/item/clothing/suit/hooded/cloak": "suit []",
  "/obj/item/clothing/suit/hooded/flashsuit": "flashy costume [flashsuit]",
  "/obj/item/clothing/suit/hooded/carp_costume": "carp costume [carp_casual]",
  "/obj/item/clothing/suit/hooded/bee_costume": "bee costume [bee]",
  "/obj/item/clothing/suit/hooded/bloated_human": "bloated human suit [lingspacesuit]",
  "/obj/item/clothing/suit/hooded/mysticrobe": "mystic's robe [mysticrobe]",
  "/obj/item/clothing/suit/hooded/techpriest": "techpriest robes [techpriest]",
  "/obj/item/clothing/suit/hooded/wintercoat/centcom": "centcom winter coat [coatcentcom]",
  "/obj/item/clothing/suit/hooded/wintercoat/captain": "captain's winter coat [coatcaptain]",
  "/obj/item/clothing/suit/hooded/wintercoat/hop": "head of personnel's winter coat [coathop]",
  "/obj/item/clothing/suit/hooded/wintercoat/hydro": "hydroponics winter coat [coathydro]",
  "/obj/item/clothing/suit/hooded/wintercoat/janitor": "janitors winter coat [coatjanitor]",
  "/obj/item/clothing/suit/hooded/wintercoat/security/hos": "head of security's winter coat [coathos]",
  "/obj/item/clothing/suit/hooded/wintercoat/security": "security winter coat [coatsecurity]",
  "/obj/item/clothing/suit/hooded/wintercoat/medical/cmo": "chief medical officer's winter coat [coatcmo]",
  "/obj/item/clothing/suit/hooded/wintercoat/medical/chemistry": "chemistry winter coat [coatchemistry]",
  "/obj/item/clothing/suit/hooded/wintercoat/medical/viro": "virology winter coat [coatviro]",
  "/obj/item/clothing/suit/hooded/wintercoat/medical/paramedic": "paramedic winter coat [coatparamed]",
  "/obj/item/clothing/suit/hooded/wintercoat/medical": "medical winter coat [coatmedical]",
  "/obj/item/clothing/suit/hooded/wintercoat/science/rd": "research director's winter coat [coatrd]",
  "/obj/item/clothing/suit/hooded/wintercoat/science/robotics": "robotics winter coat [coatrobotics]",
  "/obj/item/clothing/suit/hooded/wintercoat/science/genetics": "genetics winter coat [coatgenetics]",
  "/obj/item/clothing/suit/hooded/wintercoat/science": "science winter coat [coatscience]",
  "/obj/item/clothing/suit/hooded/wintercoat/engineering/ce": "chief engineer's winter coat [coatce]",
  "/obj/item/clothing/suit/hooded/wintercoat/engineering/atmos": "atmospherics winter coat [coatatmos]",
  "/obj/item/clothing/suit/hooded/wintercoat/engineering": "engineering winter coat [coatengineer]",
  "/obj/item/clothing/suit/hooded/wintercoat/cargo": "cargo winter coat [coatcargo]",
  "/obj/item/clothing/suit/hooded/wintercoat/qm": "quartermaster's winter coat [coatqm]",
  "/obj/item/clothing/suit/hooded/wintercoat/miner": "mining winter coat [coatminer]",
  "/obj/item/clothing/suit/hooded/wintercoat/custom": "tailored winter coat [coatwinter]",
  "/obj/item/clothing/suit/hooded/wintercoat": "winter coat [coatwinter]",
  "/obj/item/clothing/suit/hooded/explorer": "explorer suit [explorer]",
  "/obj/item/clothing/suit/hooded": "suit []",
  "/obj/item/clothing/suit/armor/riot/chaplain/clock": "forgotten armour [clockwork_cuirass]",
  "/obj/item/clothing/suit/armor/riot/chaplain/studentuni": "student robe [studentuni]",
  "/obj/item/clothing/suit/armor/riot/chaplain/ancient": "ancient armour [knight_ancient]",
  "/obj/item/clothing/suit/armor/riot/chaplain/witchhunter": "witchunter garb [witchhunter]",
  "/obj/item/clothing/suit/armor/riot/chaplain/adept": "adept robes [crusader]",
  "/obj/item/clothing/suit/armor/riot/chaplain": "crusader armour [knight_templar]",
  "/obj/item/clothing/suit/armor/riot/knight/yellow": "plate armour [knight_yellow]",
  "/obj/item/clothing/suit/armor/riot/knight/blue": "plate armour [knight_blue]",
  "/obj/item/clothing/suit/armor/riot/knight/red": "plate armour [knight_red]",
  "/obj/item/clothing/suit/armor/riot/knight/greyscale": "knight armour [knight_greyscale]",
  "/obj/item/clothing/suit/armor/riot/knight": "plate armour [knight_green]",
  "/obj/item/clothing/suit/armor/riot": "riot suit [riot]",
  "/obj/item/clothing/suit/armor/plate/crusader/red": "Crusader's Armour [crusader-red]",
  "/obj/item/clothing/suit/armor/plate/crusader/blue": "Crusader's Armour [crusader-blue]",
  "/obj/item/clothing/suit/armor/plate/crusader": "Crusader's Armour [crusader]",
  "/obj/item/clothing/suit/armor/plate": "suit []",
  "/obj/item/clothing/suit/armor/abductor/vest": "agent vest [vest_stealth]",
  "/obj/item/clothing/suit/armor/abductor": "suit []",
  "/obj/item/clothing/suit/armor/changeling": "chitinous mass [lingarmor]",
  "/obj/item/clothing/suit/armor/vest/alt": "armor vest [armor]",
  "/obj/item/clothing/suit/armor/vest/marine/security": "marine heavy armor [marine_security]",
  "/obj/item/clothing/suit/armor/vest/marine/engineer": "marine utility armor [marine_engineer]",
  "/obj/item/clothing/suit/armor/vest/marine/medic": "marine medic armor [marine_medic]",
  "/obj/item/clothing/suit/armor/vest/marine": "marine combat armor [marine_command]",
  "/obj/item/clothing/suit/armor/vest/old": "degrading armor vest [armor]",
  "/obj/item/clothing/suit/armor/vest/blueshirt": "large armor vest [blueshift]",
  "/obj/item/clothing/suit/armor/vest/cuirass": "cuirass [cuirass]",
  "/obj/item/clothing/suit/armor/vest/warden/alt": "warden's armored jacket [warden_jacket]",
  "/obj/item/clothing/suit/armor/vest/warden": "warden's jacket [warden_alt]",
  "/obj/item/clothing/suit/armor/vest/leather": "security overcoat [leathercoat-sec]",
  "/obj/item/clothing/suit/armor/vest/capcarapace/syndicate": "syndicate captain's vest [syndievest]",
  "/obj/item/clothing/suit/armor/vest/capcarapace": "captain's carapace [capcarapace]",
  "/obj/item/clothing/suit/armor/vest/det_suit": "detective's armor vest [detective-armor]",
  "/obj/item/clothing/suit/armor/vest/infiltrator": "infiltrator vest [infiltrator]",
  "/obj/item/clothing/suit/armor/vest/durathread": "durathread vest [durathread]",
  "/obj/item/clothing/suit/armor/vest/russian": "russian vest [rus_armor]",
  "/obj/item/clothing/suit/armor/vest/russian_coat": "russian battle coat [rus_coat]",
  "/obj/item/clothing/suit/armor/vest": "armor vest [armoralt]",
  "/obj/item/clothing/suit/armor/hos/trenchcoat": "armored trenchcoat [hostrench]",
  "/obj/item/clothing/suit/armor/hos": "armored greatcoat [hos]",
  "/obj/item/clothing/suit/armor/bone": "bone armor [bonearmor]",
  "/obj/item/clothing/suit/armor/bulletproof": "bulletproof armor [bulletproof]",
  "/obj/item/clothing/suit/armor/laserproof": "reflector vest [armor_reflec]",
  "/obj/item/clothing/suit/armor/heavy/adamantine": "adamantine armor [adamsuit]",
  "/obj/item/clothing/suit/armor/heavy": "heavy armor [heavy]",
  "/obj/item/clothing/suit/armor/tdome/red": "thunderdome suit [tdred]",
  "/obj/item/clothing/suit/armor/tdome/green": "thunderdome suit [tdgreen]",
  "/obj/item/clothing/suit/armor/tdome/holosuit/red": "thunderdome suit [tdred]",
  "/obj/item/clothing/suit/armor/tdome/holosuit/green": "thunderdome suit [tdgreen]",
  "/obj/item/clothing/suit/armor/tdome/holosuit": "thunderdome suit []",
  "/obj/item/clothing/suit/armor/tdome": "suit []",
  "/obj/item/clothing/suit/armor/elder_atmosian": "Elder Atmosian Armor [h2armor]",
  "/obj/item/clothing/suit/armor/reactive/teleport": "reactive teleport armor [reactiveoff]",
  "/obj/item/clothing/suit/armor/reactive/fire": "reactive incendiary armor [reactiveoff]",
  "/obj/item/clothing/suit/armor/reactive/stealth": "reactive stealth armor [reactiveoff]",
  "/obj/item/clothing/suit/armor/reactive/tesla": "reactive tesla armor [reactiveoff]",
  "/obj/item/clothing/suit/armor/reactive/repulse": "reactive repulse armor [reactiveoff]",
  "/obj/item/clothing/suit/armor/reactive/table": "reactive table armor [reactiveoff]",
  "/obj/item/clothing/suit/armor/reactive": "reactive armor [reactiveoff]",
  "/obj/item/clothing/suit/armor": "suit []",
  "/obj/item/clothing/suit/space/changeling": "flesh mass [lingspacesuit]",
  "/obj/item/clothing/suit/space/hardsuit/cult/real": "Nar'Sien hardened armor [cult_armor]",
  "/obj/item/clothing/suit/space/hardsuit/cult": "Nar'Sien hardened armor [cult_armor]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/light/red": "light red shielded hardsuit [ert_security]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/light/blue": "light blue shielded hardsuit [ert_command]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/light/green": "light green shielded hardsuit [ert_green]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/light/yellow": "light yellow shielded hardsuit [ert_engineer]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/light": "light white shielded hardsuit [ert_medical]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/red": "red shielded hardsuit [ert_security]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/blue": "blue shielded hardsuit [ert_command]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/green": "green shielded hardsuit [ert_green]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf/yellow": "yellow shielded hardsuit [ert_engineer]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/ctf": "white shielded hardsuit [ert_medical]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/syndi": "blood-red hardsuit [hardsuit1-syndi]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/swat": "death commando spacesuit [deathsquad]",
  "/obj/item/clothing/suit/space/hardsuit/shielded/wizard": "battlemage armour [battlemage]",
  "/obj/item/clothing/suit/space/hardsuit/shielded": "shielded hardsuit [hardsuit-hos]",
  "/obj/item/clothing/suit/space/hardsuit/engine/atmos": "atmospherics hardsuit [hardsuit-atmospherics]",
  "/obj/item/clothing/suit/space/hardsuit/engine/elite": "advanced hardsuit [hardsuit-white]",
  "/obj/item/clothing/suit/space/hardsuit/engine": "engineering hardsuit [hardsuit-engineering]",
  "/obj/item/clothing/suit/space/hardsuit/mining": "mining hardsuit [hardsuit-mining]",
  "/obj/item/clothing/suit/space/hardsuit/syndi/elite/debug": "elite syndicate hardsuit [hardsuit1-syndielite]",
  "/obj/item/clothing/suit/space/hardsuit/syndi/elite/admin": "jannie hardsuit [hardsuit1-syndielite]",
  "/obj/item/clothing/suit/space/hardsuit/syndi/elite": "elite syndicate hardsuit [hardsuit1-syndielite]",
  "/obj/item/clothing/suit/space/hardsuit/syndi/owl": "owl hardsuit [hardsuit1-owl]",
  "/obj/item/clothing/suit/space/hardsuit/syndi": "blood-red hardsuit [hardsuit1-syndi]",
  "/obj/item/clothing/suit/space/hardsuit/wizard": "gem-encrusted hardsuit [hardsuit-wiz]",
  "/obj/item/clothing/suit/space/hardsuit/medical": "medical hardsuit [hardsuit-medical]",
  "/obj/item/clothing/suit/space/hardsuit/rd": "prototype hardsuit [hardsuit-rd]",
  "/obj/item/clothing/suit/space/hardsuit/security/hos": "head of security's hardsuit [hardsuit-hos]",
  "/obj/item/clothing/suit/space/hardsuit/security": "security hardsuit [hardsuit-sec]",
  "/obj/item/clothing/suit/space/hardsuit/swat/captain": "captain's SWAT suit [caparmor]",
  "/obj/item/clothing/suit/space/hardsuit/swat/centcom": "CentCom SWAT armor [centcom]",
  "/obj/item/clothing/suit/space/hardsuit/swat": "MK.II SWAT Suit [swat2]",
  "/obj/item/clothing/suit/space/hardsuit/clown": "cosmohonk hardsuit [hardsuit-clown]",
  "/obj/item/clothing/suit/space/hardsuit/ancient": "prototype RIG hardsuit [hardsuit-ancient]",
  "/obj/item/clothing/suit/space/hardsuit/deathsquad": "MK.III SWAT Suit [deathsquad]",
  "/obj/item/clothing/suit/space/hardsuit/ert/sec": "emergency response team security hardsuit [ert_security]",
  "/obj/item/clothing/suit/space/hardsuit/ert/engi": "emergency response team engineering hardsuit [ert_engineer]",
  "/obj/item/clothing/suit/space/hardsuit/ert/med": "emergency response team medical hardsuit [ert_medical]",
  "/obj/item/clothing/suit/space/hardsuit/ert/jani": "emergency response team janitorial hardsuit [ert_janitor]",
  "/obj/item/clothing/suit/space/hardsuit/ert/clown": "emergency response team clown hardsuit [ert_clown]",
  "/obj/item/clothing/suit/space/hardsuit/ert/paranormal/inquisitor": "inquisitor's hardsuit [hardsuit-inq]",
  "/obj/item/clothing/suit/space/hardsuit/ert/paranormal": "paranormal response team hardsuit [knight_grey]",
  "/obj/item/clothing/suit/space/hardsuit/ert": "emergency response team commander hardsuit [ert_command]",
  "/obj/item/clothing/suit/space/hardsuit/carp/old": "battered carp space suit [carp_suit]",
  "/obj/item/clothing/suit/space/hardsuit/carp": "carp space suit [carp_suit]",
  "/obj/item/clothing/suit/space/hardsuit/combatmedic": "endemic combat medic hardsuit [combatmedic]",
  "/obj/item/clothing/suit/space/hardsuit/hostile_environment": "H.E.C.K. suit [hostile_env]",
  "/obj/item/clothing/suit/space/hardsuit/berserker": "berserker hardsuit [hardsuit-berserker]",
  "/obj/item/clothing/suit/space/hardsuit/cybersun": "Cybersun hardsuit [cybersun]",
  "/obj/item/clothing/suit/space/hardsuit": "hardsuit [hardsuit-engineering]",
  "/obj/item/clothing/suit/space/hunter": "bounty hunting suit [hunter]",
  "/obj/item/clothing/suit/space/chronos": "Chronosuit [chronosuit]",
  "/obj/item/clothing/suit/space/freedom": "eagle suit [freedom]",
  "/obj/item/clothing/suit/space/pirate": "modified EVA suit [spacepirate]",
  "/obj/item/clothing/suit/space/eva/plasmaman": "EVA plasma envirosuit [plasmaman_suit]",
  "/obj/item/clothing/suit/space/eva": "EVA suit [space]",
  "/obj/item/clothing/suit/space/santa": "Santa's suit [santa]",
  "/obj/item/clothing/suit/space/nasavoid/old": "Engineering Voidsuit [void]",
  "/obj/item/clothing/suit/space/nasavoid": "NASA Voidsuit [void]",
  "/obj/item/clothing/suit/space/fragile": "emergency space suit [syndicate-orange]",
  "/obj/item/clothing/suit/space/officer": "officer's jacket [detective]",
  "/obj/item/clothing/suit/space/swat": "MK.I SWAT Suit [heavy]",
  "/obj/item/clothing/suit/space/syndicate/green/dark": "dark green space suit [syndicate-green-dark]",
  "/obj/item/clothing/suit/space/syndicate/green": "green space suit [syndicate-green]",
  "/obj/item/clothing/suit/space/syndicate/orange": "orange space suit [syndicate-orange]",
  "/obj/item/clothing/suit/space/syndicate/blue": "blue space suit [syndicate-blue]",
  "/obj/item/clothing/suit/space/syndicate/black/green": "black and green space suit [syndicate-black-green]",
  "/obj/item/clothing/suit/space/syndicate/black/blue": "black and blue space suit [syndicate-black-blue]",
  "/obj/item/clothing/suit/space/syndicate/black/med": "green space suit [syndicate-black-med]",
  "/obj/item/clothing/suit/space/syndicate/black/orange": "black and orange space suit [syndicate-black-orange]",
  "/obj/item/clothing/suit/space/syndicate/black/red": "black and red space suit [syndicate-black-red]",
  "/obj/item/clothing/suit/space/syndicate/black/engie": "black engineering space suit [syndicate-black-engie]",
  "/obj/item/clothing/suit/space/syndicate/black": "black space suit [syndicate-black]",
  "/obj/item/clothing/suit/space/syndicate/contract": "contractor space suit [syndicate-contract]",
  "/obj/item/clothing/suit/space/syndicate": "red space suit [syndicate]",
  "/obj/item/clothing/suit/space/space_ninja": "ninja suit [s-ninja]",
  "/obj/item/clothing/suit/space/orange": "emergency space suit [syndicate-orange]",
  "/obj/item/clothing/suit/space": "space suit [spaceold]",
  "/obj/item/clothing/suit/changeling": "flesh []",
  "/obj/item/clothing/suit/magusred": "magus robes [magusred]",
  "/obj/item/clothing/suit/chameleon/broken": "armor [armor]",
  "/obj/item/clothing/suit/chameleon": "armor [armor]",
  "/obj/item/clothing/suit/toggle/captains_parade": "captain's parade jacket [capformal]",
  "/obj/item/clothing/suit/toggle/armor/vest/centcom_formal": "CentCom formal coat [centcom_formal]",
  "/obj/item/clothing/suit/toggle/armor/vest": "suit []",
  "/obj/item/clothing/suit/toggle/armor/hos/hos_formal": "Head of Security's parade jacket [hosformal]",
  "/obj/item/clothing/suit/toggle/armor/hos": "suit []",
  "/obj/item/clothing/suit/toggle/armor": "suit []",
  "/obj/item/clothing/suit/toggle/owlwings/griffinwings": "griffon cloak [griffin_wings]",
  "/obj/item/clothing/suit/toggle/owlwings": "owl cloak [owl_wings]",
  "/obj/item/clothing/suit/toggle/chef": "chef's apron [chef]",
  "/obj/item/clothing/suit/toggle/lawyer/purple": "purple suit jacket [suitjacket_purp]",
  "/obj/item/clothing/suit/toggle/lawyer/black": "black suit jacket [suitjacket_black]",
  "/obj/item/clothing/suit/toggle/lawyer": "blue suit jacket [suitjacket_blue]",
  "/obj/item/clothing/suit/toggle/suspenders/blue": "blue suspenders [suspenders]",
  "/obj/item/clothing/suit/toggle/suspenders/gray": "gray suspenders [suspenders]",
  "/obj/item/clothing/suit/toggle/suspenders": "suspenders [suspenders]",
  "/obj/item/clothing/suit/toggle/labcoat/cmo": "chief medical officer's labcoat [labcoat_cmo]",
  "/obj/item/clothing/suit/toggle/labcoat/paramedic": "paramedic's jacket [labcoat_paramedic]",
  "/obj/item/clothing/suit/toggle/labcoat/mad": "The Mad's labcoat [labgreen]",
  "/obj/item/clothing/suit/toggle/labcoat/genetics": "geneticist labcoat [labcoat_gen]",
  "/obj/item/clothing/suit/toggle/labcoat/chemist": "chemist labcoat [labcoat_chem]",
  "/obj/item/clothing/suit/toggle/labcoat/virologist": "virologist labcoat [labcoat_vir]",
  "/obj/item/clothing/suit/toggle/labcoat/science": "scientist labcoat [labcoat_sci]",
  "/obj/item/clothing/suit/toggle/labcoat/roboticist": "roboticist labcoat [labcoat_robo]",
  "/obj/item/clothing/suit/toggle/labcoat": "labcoat [labcoat]",
  "/obj/item/clothing/suit/toggle": "suit []",
  "/obj/item/clothing/suit/bio_suit/general": "bio suit [bio_general]",
  "/obj/item/clothing/suit/bio_suit/virology": "bio suit [bio_virology]",
  "/obj/item/clothing/suit/bio_suit/security": "bio suit [bio_security]",
  "/obj/item/clothing/suit/bio_suit/janitor": "bio suit [bio_janitor]",
  "/obj/item/clothing/suit/bio_suit/scientist": "bio suit [bio_scientist]",
  "/obj/item/clothing/suit/bio_suit/cmo": "bio suit [bio_cmo]",
  "/obj/item/clothing/suit/bio_suit/plaguedoctorsuit": "plague doctor suit [plaguedoctor]",
  "/obj/item/clothing/suit/bio_suit": "bio suit [bio]",
  "/obj/item/clothing/suit/chaplainsuit/holidaypriest": "holiday priest [holidaypriest]",
  "/obj/item/clothing/suit/chaplainsuit/nun": "nun robe [nun]",
  "/obj/item/clothing/suit/chaplainsuit/bishoprobe": "bishop's robes [bishoprobe]",
  "/obj/item/clothing/suit/chaplainsuit/studentuni": "student robe [studentuni]",
  "/obj/item/clothing/suit/chaplainsuit/witchhunter": "witchunter garb [witchhunter]",
  "/obj/item/clothing/suit/chaplainsuit/monkrobeeast": "eastern monk's robes [monkrobeeast]",
  "/obj/item/clothing/suit/chaplainsuit/whiterobe": "white robe [whiterobe]",
  "/obj/item/clothing/suit/chaplainsuit/clownpriest": "Robes of the Honkmother [clownpriest]",
  "/obj/item/clothing/suit/chaplainsuit": "suit []",
  "/obj/item/clothing/suit/pirate/armored": "pirate coat [pirate]",
  "/obj/item/clothing/suit/pirate/captain/armored": "pirate captain coat [hgpirate]",
  "/obj/item/clothing/suit/pirate/captain": "pirate captain coat [hgpirate]",
  "/obj/item/clothing/suit/pirate": "pirate coat [pirate]",
  "/obj/item/clothing/suit/cyborg_suit": "cyborg suit [death]",
  "/obj/item/clothing/suit/justice": "justice suit [justice]",
  "/obj/item/clothing/suit/judgerobe": "judge's robe [judge]",
  "/obj/item/clothing/suit/apron/overalls": "coveralls [overalls]",
  "/obj/item/clothing/suit/apron/purple_bartender": "purple bartender apron [purplebartenderapron]",
  "/obj/item/clothing/suit/apron/waders": "horticultural waders [hort_waders]",
  "/obj/item/clothing/suit/apron/chef": "cook's apron [apronchef]",
  "/obj/item/clothing/suit/apron/surgical": "surgical apron [surgical]",
  "/obj/item/clothing/suit/apron": "apron [apron]",
  "/obj/item/clothing/suit/syndicatefake": "black and red space suit replica [syndicate-black-red]",
  "/obj/item/clothing/suit/hastur": "Hastur's robe [hastur]",
  "/obj/item/clothing/suit/imperium_monk": "Imperium monk suit [imperium_monk]",
  "/obj/item/clothing/suit/chickensuit": "chicken suit [chickensuit]",
  "/obj/item/clothing/suit/monkeysuit": "monkey suit [monkeysuit]",
  "/obj/item/clothing/suit/cardborg": "cardborg suit [cardborg]",
  "/obj/item/clothing/suit/snowman": "snowman outfit [snowman]",
  "/obj/item/clothing/suit/poncho/green": "green poncho [greenponcho]",
  "/obj/item/clothing/suit/poncho/red": "red poncho [redponcho]",
  "/obj/item/clothing/suit/poncho/ponchoshame": "poncho of shame [ponchoshame]",
  "/obj/item/clothing/suit/poncho": "poncho [classicponcho]",
  "/obj/item/clothing/suit/whitedress": "white dress [white_dress]",
  "/obj/item/clothing/suit/security/officer/russian": "Russian officer's jacket [officertanjacket]",
  "/obj/item/clothing/suit/security/officer": "security officer's jacket [officerbluejacket]",
  "/obj/item/clothing/suit/security/warden": "warden's jacket [wardenbluejacket]",
  "/obj/item/clothing/suit/security/hos": "head of security's jacket [hosbluejacket]",
  "/obj/item/clothing/suit/security": "suit []",
  "/obj/item/clothing/suit/shrine_maiden": "shrine maiden's outfit [shrine_maiden]",
  "/obj/item/clothing/suit/striped_sweater": "striped sweater [waldo_shirt]",
  "/obj/item/clothing/suit/dracula": "dracula coat [draculacoat]",
  "/obj/item/clothing/suit/drfreeze_coat": "doctor freeze's labcoat [drfreeze_coat]",
  "/obj/item/clothing/suit/gothcoat": "gothic coat [gothcoat]",
  "/obj/item/clothing/suit/xenos": "xenos suit [xenos]",
  "/obj/item/clothing/suit/nemes": "pharoah tunic [pharoah]",
  "/obj/item/clothing/suit/changshan_red": "red changshan [changshan_red]",
  "/obj/item/clothing/suit/changshan_blue": "blue changshan [changshan_blue]",
  "/obj/item/clothing/suit/cheongsam_red": "red cheongsam [cheongsam_red]",
  "/obj/item/clothing/suit/cheongsam_blue": "blue cheongsam [cheongsam_blue]",
  "/obj/item/clothing/suit/bronze": "bronze suit [clockwork_cuirass_old]",
  "/obj/item/clothing/suit/coordinator": "coordinator jacket [capformal]",
  "/obj/item/clothing/suit/hawaiian": "hawaiian overshirt [hawaiian_blue]",
  "/obj/item/clothing/suit/yakuza": "tojo clan jacket [MajimaJacket]",
  "/obj/item/clothing/suit/dutch": "dutch's jacket [DutchJacket]",
  "/obj/item/clothing/suit/ghost_sheet/spooky": "spooky ghost [ghost_sheet]",
  "/obj/item/clothing/suit/ghost_sheet": "ghost sheet [ghost_sheet]",
  "/obj/item/clothing/suit/jacket/leather/overcoat": "leather overcoat [leathercoat]",
  "/obj/item/clothing/suit/jacket/leather": "leather jacket [leatherjacket]",
  "/obj/item/clothing/suit/jacket/puffer/vest": "puffer vest [puffervest]",
  "/obj/item/clothing/suit/jacket/puffer": "puffer jacket [pufferjacket]",
  "/obj/item/clothing/suit/jacket/miljacket": "military jacket [militaryjacket]",
  "/obj/item/clothing/suit/jacket/letterman": "letterman jacket [letterman]",
  "/obj/item/clothing/suit/jacket/letterman_red": "red letterman jacket [letterman_red]",
  "/obj/item/clothing/suit/jacket/letterman_syndie": "blood-red letterman jacket [letterman_s]",
  "/obj/item/clothing/suit/jacket/letterman_nanotrasen": "blue letterman jacket [letterman_n]",
  "/obj/item/clothing/suit/jacket": "bomber jacket [bomberjacket]",
  "/obj/item/clothing/suit/captunic": "captain's parade tunic [captunic]",
  "/obj/item/clothing/suit/det_suit/grey": "noir trenchcoat [greydet]",
  "/obj/item/clothing/suit/det_suit/noir": "noir suit coat [detsuit]",
  "/obj/item/clothing/suit/det_suit": "trenchcoat [detective]",
  "/obj/item/clothing/suit/hazardvest": "hazard vest [hazard]",
  "/obj/item/clothing/suit/curator": "treasure hunter's coat [curator]",
  "/obj/item/clothing/suit/bluetag": "blue laser tag armor [bluetag]",
  "/obj/item/clothing/suit/redtag": "red laser tag armor [redtag]",
  "/obj/item/clothing/suit/ianshirt": "worn shirt [ianshirt]",
  "/obj/item/clothing/suit/nerdshirt": "gamer shirt [nerdshirt]",
  "/obj/item/clothing/suit/vapeshirt": "Vape Naysh shirt [vapeshirt]",
  "/obj/item/clothing/suit/straight_jacket": "straight jacket [straight_jacket]",
  "/obj/item/clothing/suit/fire/firefighter": "emergency firesuit [firesuit]",
  "/obj/item/clothing/suit/fire/heavy": "heavy firesuit [thermal]",
  "/obj/item/clothing/suit/fire/atmos": "firesuit [atmos_firesuit]",
  "/obj/item/clothing/suit/fire": "emergency firesuit [fire]",
  "/obj/item/clothing/suit/bomb_suit/security": "bomb suit [bombsuit_sec]",
  "/obj/item/clothing/suit/bomb_suit/white": "bomb suit [bombsuit_white]",
  "/obj/item/clothing/suit/bomb_suit": "bomb suit [bombsuit]",
  "/obj/item/clothing/suit/radiation": "radiation suit [rad]",
  "/obj/item/clothing/suit/caution": "wet floor sign [caution]",
  "/obj/item/clothing/suit/wizrobe/red": "red wizard robe [redwizard]",
  "/obj/item/clothing/suit/wizrobe/yellow": "yellow wizard robe [yellowwizard]",
  "/obj/item/clothing/suit/wizrobe/black": "black wizard robe [blackwizard]",
  "/obj/item/clothing/suit/wizrobe/marisa/fake": "witch robe [marisa]",
  "/obj/item/clothing/suit/wizrobe/marisa": "witch robe [marisa]",
  "/obj/item/clothing/suit/wizrobe/magusblue": "Magus robe [magusblue]",
  "/obj/item/clothing/suit/wizrobe/magusred": "Magus robe [magusred]",
  "/obj/item/clothing/suit/wizrobe/santa": "Santa's suit [santa]",
  "/obj/item/clothing/suit/wizrobe/fake": "wizard robe [wizard-fake]",
  "/obj/item/clothing/suit/wizrobe/paper": "papier-mache robe [wizard-paper]",
  "/obj/item/clothing/suit/wizrobe": "wizard robe [wizard]",
  "/obj/item/clothing/suit/bunnysuit": "Easter Bunny Suit [bunnysuit]",
  "/obj/item/clothing/suit/beekeeper_suit": "beekeeper suit [beekeeper]",
  "/obj/item/clothing/suit": "suit []"
}
