outfit_options["uniform"] = {
  "/obj/item/clothing/under/abductor": "alien jumpsuit [abductor]",
  "/obj/item/clothing/under/changeling": "flesh []",
  "/obj/item/clothing/under/syndicate/coldres": "insulated tactical turtleneck [syndicate]",
  "/obj/item/clothing/under/syndicate/skirt": "tactical skirtleneck [syndicate_skirt]",
  "/obj/item/clothing/under/syndicate/bloodred/sleepytime": "blood-red pajamas [bloodred_pajamas]",
  "/obj/item/clothing/under/syndicate/bloodred": "blood-red sneaksuit [bloodred_pajamas]",
  "/obj/item/clothing/under/syndicate/tacticool/skirt": "tacticool skirtleneck [tactifool_skirt]",
  "/obj/item/clothing/under/syndicate/tacticool": "tacticool turtleneck [tactifool]",
  "/obj/item/clothing/under/syndicate/sniper": "Tactical turtleneck suit [really_black_suit]",
  "/obj/item/clothing/under/syndicate/camo": "camouflage fatigues [camogreen]",
  "/obj/item/clothing/under/syndicate/soviet": "Ratnik 5 tracksuit [trackpants]",
  "/obj/item/clothing/under/syndicate/combat": "combat uniform [syndicate_combat]",
  "/obj/item/clothing/under/syndicate/rus_army": "advanced military tracksuit [rus_under]",
  "/obj/item/clothing/under/syndicate": "tactical turtleneck [syndicate]",
  "/obj/item/clothing/under/chameleon/broken": "black jumpsuit [chameleon_broken]",
  "/obj/item/clothing/under/chameleon": "black jumpsuit [chameleon]",
  "/obj/item/clothing/under/rank/cargo/qm/skirt": "quartermaster's jumpskirt [qm_skirt]",
  "/obj/item/clothing/under/rank/cargo/qm": "quartermaster's jumpsuit [qm]",
  "/obj/item/clothing/under/rank/cargo/tech/skirt": "cargo technician's jumpskirt [cargo_skirt]",
  "/obj/item/clothing/under/rank/cargo/tech": "cargo technician's jumpsuit [cargotech]",
  "/obj/item/clothing/under/rank/cargo/miner/lavaland": "shaft miner's jumpsuit [explorer]",
  "/obj/item/clothing/under/rank/cargo/miner": "shaft miner's jumpsuit [miner]",
  "/obj/item/clothing/under/rank/cargo": "under []",
  "/obj/item/clothing/under/rank/centcom/commander": "CentCom officer's jumpsuit [centcom]",
  "/obj/item/clothing/under/rank/centcom/intern": "CentCom intern's jumpsuit [intern]",
  "/obj/item/clothing/under/rank/centcom/officer/replica": "CentCom turtleneck replica [officer]",
  "/obj/item/clothing/under/rank/centcom/officer": "CentCom turtleneck suit [officer]",
  "/obj/item/clothing/under/rank/centcom/officer_skirt/replica": "CentCom turtleneck skirt replica [officer_skirt]",
  "/obj/item/clothing/under/rank/centcom/officer_skirt": "CentCom turtleneck skirt [officer_skirt]",
  "/obj/item/clothing/under/rank/centcom/centcom_skirt": "CentCom officer's jumpskirt [centcom_skirt]",
  "/obj/item/clothing/under/rank/centcom": "under []",
  "/obj/item/clothing/under/rank/captain/skirt": "captain's jumpskirt [captain_skirt]",
  "/obj/item/clothing/under/rank/captain/suit/skirt": "green suitskirt [green_suit_skirt]",
  "/obj/item/clothing/under/rank/captain/suit": "captain's suit [green_suit]",
  "/obj/item/clothing/under/rank/captain/parade": "captain's parade uniform [captain_parade]",
  "/obj/item/clothing/under/rank/captain": "captain's jumpsuit [captain]",
  "/obj/item/clothing/under/rank/engineering/chief_engineer/skirt": "chief engineer's jumpskirt [chief_skirt]",
  "/obj/item/clothing/under/rank/engineering/chief_engineer": "chief engineer's jumpsuit [chiefengineer]",
  "/obj/item/clothing/under/rank/engineering/atmospheric_technician/skirt": "atmospheric technician's jumpskirt [atmos_skirt]",
  "/obj/item/clothing/under/rank/engineering/atmospheric_technician": "atmospheric technician's jumpsuit [atmos]",
  "/obj/item/clothing/under/rank/engineering/engineer/hazard": "engineer's hazard jumpsuit [hazard]",
  "/obj/item/clothing/under/rank/engineering/engineer/skirt": "engineer's jumpskirt [engine_skirt]",
  "/obj/item/clothing/under/rank/engineering/engineer": "engineer's jumpsuit [engine]",
  "/obj/item/clothing/under/rank/engineering": "under []",
  "/obj/item/clothing/under/rank/medical/chief_medical_officer/skirt": "chief medical officer's jumpskirt [cmo_skirt]",
  "/obj/item/clothing/under/rank/medical/chief_medical_officer": "chief medical officer's jumpsuit [cmo]",
  "/obj/item/clothing/under/rank/medical/virologist/skirt": "virologist's jumpskirt [virologywhite_skirt]",
  "/obj/item/clothing/under/rank/medical/virologist": "virologist's jumpsuit [virology]",
  "/obj/item/clothing/under/rank/medical/doctor/nurse": "nurse's suit [nursesuit]",
  "/obj/item/clothing/under/rank/medical/doctor/blue": "medical scrubs [scrubsblue]",
  "/obj/item/clothing/under/rank/medical/doctor/green": "medical scrubs [scrubsgreen]",
  "/obj/item/clothing/under/rank/medical/doctor/purple": "medical scrubs [scrubspurple]",
  "/obj/item/clothing/under/rank/medical/doctor/skirt": "medical doctor's jumpskirt [medical_skirt]",
  "/obj/item/clothing/under/rank/medical/doctor": "medical doctor's jumpsuit [medical]",
  "/obj/item/clothing/under/rank/medical/chemist/skirt": "chemist's jumpskirt [chemistrywhite_skirt]",
  "/obj/item/clothing/under/rank/medical/chemist": "chemist's jumpsuit [chemistry]",
  "/obj/item/clothing/under/rank/medical/paramedic/skirt": "paramedic jumpskirt [paramedic_skirt]",
  "/obj/item/clothing/under/rank/medical/paramedic": "paramedic jumpsuit [paramedic]",
  "/obj/item/clothing/under/rank/medical": "under []",
  "/obj/item/clothing/under/rank/rnd/research_director/doctor_hilbert": "research director's vest suit [director]",
  "/obj/item/clothing/under/rank/rnd/research_director/skirt": "research director's vest suitskirt [director_skirt]",
  "/obj/item/clothing/under/rank/rnd/research_director/alt/skirt": "research director's tan suitskirt [rdwhimsy_skirt]",
  "/obj/item/clothing/under/rank/rnd/research_director/alt": "research director's tan suit [rdwhimsy]",
  "/obj/item/clothing/under/rank/rnd/research_director/turtleneck/skirt": "research director's turtleneck skirt [rdturtle_skirt]",
  "/obj/item/clothing/under/rank/rnd/research_director/turtleneck": "research director's turtleneck [rdturtle]",
  "/obj/item/clothing/under/rank/rnd/research_director": "research director's vest suit [director]",
  "/obj/item/clothing/under/rank/rnd/scientist/skirt": "scientist's jumpskirt [sciwhite_skirt]",
  "/obj/item/clothing/under/rank/rnd/scientist": "scientist's jumpsuit [science]",
  "/obj/item/clothing/under/rank/rnd/roboticist/skirt": "roboticist's jumpskirt [robotics_skirt]",
  "/obj/item/clothing/under/rank/rnd/roboticist": "roboticist's jumpsuit [robotics]",
  "/obj/item/clothing/under/rank/rnd/geneticist/skirt": "geneticist's jumpskirt [geneticswhite_skirt]",
  "/obj/item/clothing/under/rank/rnd/geneticist": "geneticist's jumpsuit [genetics]",
  "/obj/item/clothing/under/rank/rnd": "under []",
  "/obj/item/clothing/under/rank/security/officer/grey": "grey security jumpsuit [security]",
  "/obj/item/clothing/under/rank/security/officer/skirt": "security jumpskirt [secskirt]",
  "/obj/item/clothing/under/rank/security/officer/blueshirt": "blue shirt and tie [blueshift]",
  "/obj/item/clothing/under/rank/security/officer/formal": "security officer's formal uniform [officerblueclothes]",
  "/obj/item/clothing/under/rank/security/officer/spacepol": "police uniform [spacepol]",
  "/obj/item/clothing/under/rank/security/officer/beatcop": "space police uniform [spacepolice_families]",
  "/obj/item/clothing/under/rank/security/officer": "security jumpsuit [rsecurity]",
  "/obj/item/clothing/under/rank/security/constable": "constable outfit [constable]",
  "/obj/item/clothing/under/rank/security/warden/grey": "grey security suit [warden]",
  "/obj/item/clothing/under/rank/security/warden/skirt": "warden's suitskirt [rwarden_skirt]",
  "/obj/item/clothing/under/rank/security/warden/formal": "warden's formal uniform [wardenblueclothes]",
  "/obj/item/clothing/under/rank/security/warden": "security suit [rwarden]",
  "/obj/item/clothing/under/rank/security/detective/skirt": "detective's suitskirt [detective_skirt]",
  "/obj/item/clothing/under/rank/security/detective/grey/skirt": "noir suitskirt [greydet_skirt]",
  "/obj/item/clothing/under/rank/security/detective/grey": "noir suit [greydet]",
  "/obj/item/clothing/under/rank/security/detective": "hard-worn suit [detective]",
  "/obj/item/clothing/under/rank/security/head_of_security/skirt": "head of security's jumpskirt [rhos_skirt]",
  "/obj/item/clothing/under/rank/security/head_of_security/grey": "head of security's grey jumpsuit [hos]",
  "/obj/item/clothing/under/rank/security/head_of_security/alt/skirt": "head of security's turtleneck skirt [hosalt_skirt]",
  "/obj/item/clothing/under/rank/security/head_of_security/alt": "head of security's turtleneck [hosalt]",
  "/obj/item/clothing/under/rank/security/head_of_security/parade/female": "head of security's parade uniform [hos_parade_fem]",
  "/obj/item/clothing/under/rank/security/head_of_security/parade": "head of security's parade uniform [hos_parade_male]",
  "/obj/item/clothing/under/rank/security/head_of_security/formal": "head of security's formal uniform [hosblueclothes]",
  "/obj/item/clothing/under/rank/security/head_of_security": "head of security's jumpsuit [rhos]",
  "/obj/item/clothing/under/rank/security": "under []",
  "/obj/item/clothing/under/rank/prisoner/skirt": "prison jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/rank/prisoner": "prison jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/rank/civilian/bartender/purple": "purple bartender's uniform [purplebartender]",
  "/obj/item/clothing/under/rank/civilian/bartender/skirt": "bartender's skirt [barman_skirt]",
  "/obj/item/clothing/under/rank/civilian/bartender": "bartender's uniform [barman]",
  "/obj/item/clothing/under/rank/civilian/chaplain/skirt": "chaplain's jumpskirt [chapblack_skirt]",
  "/obj/item/clothing/under/rank/civilian/chaplain": "chaplain's jumpsuit [chaplain]",
  "/obj/item/clothing/under/rank/civilian/chef/skirt": "cook's skirt [chef_skirt]",
  "/obj/item/clothing/under/rank/civilian/chef": "cook's suit [chef]",
  "/obj/item/clothing/under/rank/civilian/head_of_personnel/skirt": "head of personnel's jumpskirt [hop_skirt]",
  "/obj/item/clothing/under/rank/civilian/head_of_personnel/suit/skirt": "teal suitskirt [teal_suit_skirt]",
  "/obj/item/clothing/under/rank/civilian/head_of_personnel/suit": "head of personnel's suit [teal_suit]",
  "/obj/item/clothing/under/rank/civilian/head_of_personnel": "head of personnel's jumpsuit [hop]",
  "/obj/item/clothing/under/rank/civilian/hydroponics/skirt": "botanist's jumpskirt [hydroponics_skirt]",
  "/obj/item/clothing/under/rank/civilian/hydroponics": "botanist's jumpsuit [hydroponics]",
  "/obj/item/clothing/under/rank/civilian/janitor/skirt": "janitor's jumpskirt [janitor_skirt]",
  "/obj/item/clothing/under/rank/civilian/janitor/maid": "maid uniform [janimaid]",
  "/obj/item/clothing/under/rank/civilian/janitor": "janitor's jumpsuit [janitor]",
  "/obj/item/clothing/under/rank/civilian/lawyer/black/skirt": "lawyer black suitskirt [lawyer_black_skirt]",
  "/obj/item/clothing/under/rank/civilian/lawyer/black": "lawyer black suit [lawyer_black]",
  "/obj/item/clothing/under/rank/civilian/lawyer/female/skirt": "female black suitskirt [black_suit_fem_skirt]",
  "/obj/item/clothing/under/rank/civilian/lawyer/female": "female black suit [black_suit_fem]",
  "/obj/item/clothing/under/rank/civilian/lawyer/red/skirt": "lawyer red suitskirt [lawyer_red_skirt]",
  "/obj/item/clothing/under/rank/civilian/lawyer/red": "lawyer red suit [lawyer_red]",
  "/obj/item/clothing/under/rank/civilian/lawyer/blue/skirt": "lawyer blue suitskirt [lawyer_blue_skirt]",
  "/obj/item/clothing/under/rank/civilian/lawyer/blue": "lawyer blue suit [lawyer_blue]",
  "/obj/item/clothing/under/rank/civilian/lawyer/bluesuit/skirt": "blue suitskirt [bluesuit_skirt]",
  "/obj/item/clothing/under/rank/civilian/lawyer/bluesuit": "blue suit [bluesuit]",
  "/obj/item/clothing/under/rank/civilian/lawyer/purpsuit/skirt": "purple suitskirt [lawyer_purp_skirt]",
  "/obj/item/clothing/under/rank/civilian/lawyer/purpsuit": "purple suit [lawyer_purp]",
  "/obj/item/clothing/under/rank/civilian/lawyer/galaxy/red": "red galaxy suit [lawyer_galaxy_red]",
  "/obj/item/clothing/under/rank/civilian/lawyer/galaxy": "blue galaxy suit [lawyer_galaxy_blue]",
  "/obj/item/clothing/under/rank/civilian/lawyer": "Lawyer suit []",
  "/obj/item/clothing/under/rank/civilian/cookjorts": "grilling shorts [cookjorts]",
  "/obj/item/clothing/under/rank/civilian/mime/skirt": "mime's skirt [mime_skirt]",
  "/obj/item/clothing/under/rank/civilian/mime/sexy": "sexy mime outfit [sexymime]",
  "/obj/item/clothing/under/rank/civilian/mime": "mime's outfit [mime]",
  "/obj/item/clothing/under/rank/civilian/clown/blue": "blue clown suit [blueclown]",
  "/obj/item/clothing/under/rank/civilian/clown/green": "green clown suit [greenclown]",
  "/obj/item/clothing/under/rank/civilian/clown/yellow": "yellow clown suit [yellowclown]",
  "/obj/item/clothing/under/rank/civilian/clown/purple": "purple clown suit [purpleclown]",
  "/obj/item/clothing/under/rank/civilian/clown/orange": "orange clown suit [orangeclown]",
  "/obj/item/clothing/under/rank/civilian/clown/rainbow": "rainbow clown suit [rainbowclown]",
  "/obj/item/clothing/under/rank/civilian/clown/jester/alt": "jester suit [jester2]",
  "/obj/item/clothing/under/rank/civilian/clown/jester": "jester suit [jester]",
  "/obj/item/clothing/under/rank/civilian/clown/sexy": "sexy-clown suit [sexyclown]",
  "/obj/item/clothing/under/rank/civilian/clown": "clown suit [clown]",
  "/obj/item/clothing/under/rank/civilian/curator/skirt": "sensible suitskirt [red_suit_skirt]",
  "/obj/item/clothing/under/rank/civilian/curator/treasure_hunter": "treasure hunter uniform [curator]",
  "/obj/item/clothing/under/rank/civilian/curator/nasa": "NASA jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/rank/civilian/curator": "sensible suit [red_suit]",
  "/obj/item/clothing/under/rank/civilian": "under []",
  "/obj/item/clothing/under/rank": "under []",
  "/obj/item/clothing/under/color/jumpskirt/random": "under [random_jumpsuit]",
  "/obj/item/clothing/under/color/jumpskirt/black": "black jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/grey": "grey jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/blue": "blue jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/green": "green jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/orange": "orange jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/pink": "pink jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/red": "red jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/white": "white jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/yellow": "yellow jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/darkblue": "dark blue jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/teal": "teal jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/lightpurple": "light purple jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/darkgreen": "dark green jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/lightbrown": "light brown jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/brown": "brown jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/maroon": "maroon jumpskirt [jumpskirt]",
  "/obj/item/clothing/under/color/jumpskirt/rainbow": "rainbow jumpskirt [rainbow_skirt]",
  "/obj/item/clothing/under/color/jumpskirt": "under []",
  "/obj/item/clothing/under/color/random": "under [random_jumpsuit]",
  "/obj/item/clothing/under/color/black/ghost": "black jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/black": "black jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/grey/ancient": "ancient jumpsuit [grey_ancient]",
  "/obj/item/clothing/under/color/grey": "grey jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/blue": "blue jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/green": "green jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/orange": "orange jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/pink": "pink jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/red": "red jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/white": "white jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/yellow": "yellow jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/darkblue": "dark blue jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/teal": "teal jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/lightpurple": "light purple jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/darkgreen": "dark green jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/lightbrown": "light brown jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/brown": "brown jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/maroon": "maroon jumpsuit [jumpsuit]",
  "/obj/item/clothing/under/color/rainbow": "rainbow jumpsuit [rainbow]",
  "/obj/item/clothing/under/color": "under []",
  "/obj/item/clothing/under/costume/roman": "Roman armor [roman]",
  "/obj/item/clothing/under/costume/jabroni": "jabroni outfit [darkholme]",
  "/obj/item/clothing/under/costume/owl": "owl uniform [owl]",
  "/obj/item/clothing/under/costume/griffin": "griffon uniform [griffin]",
  "/obj/item/clothing/under/costume/schoolgirl/red": "red schoolgirl uniform [schoolgirlred]",
  "/obj/item/clothing/under/costume/schoolgirl/green": "green schoolgirl uniform [schoolgirlgreen]",
  "/obj/item/clothing/under/costume/schoolgirl/orange": "orange schoolgirl uniform [schoolgirlorange]",
  "/obj/item/clothing/under/costume/schoolgirl": "blue schoolgirl uniform [schoolgirl]",
  "/obj/item/clothing/under/costume/pirate": "pirate outfit [pirate]",
  "/obj/item/clothing/under/costume/soviet": "soviet uniform [soviet]",
  "/obj/item/clothing/under/costume/redcoat": "redcoat uniform [redcoat]",
  "/obj/item/clothing/under/costume/kilt/highlander": "kilt [kilt]",
  "/obj/item/clothing/under/costume/kilt": "kilt [kilt]",
  "/obj/item/clothing/under/costume/gladiator/ash_walker": "gladiator uniform [gladiator]",
  "/obj/item/clothing/under/costume/gladiator": "gladiator uniform [gladiator]",
  "/obj/item/clothing/under/costume/maid": "maid costume [maid]",
  "/obj/item/clothing/under/costume/geisha": "geisha suit [geisha]",
  "/obj/item/clothing/under/costume/villain": "villain suit [villain]",
  "/obj/item/clothing/under/costume/sailor": "sailor suit [sailor]",
  "/obj/item/clothing/under/costume/singer/yellow": "yellow performer's outfit [ysing]",
  "/obj/item/clothing/under/costume/singer/blue": "blue performer's outfit [bsing]",
  "/obj/item/clothing/under/costume/singer": "under []",
  "/obj/item/clothing/under/costume/mummy": "mummy wrapping [mummy]",
  "/obj/item/clothing/under/costume/scarecrow": "scarecrow clothes [scarecrow]",
  "/obj/item/clothing/under/costume/draculass": "draculass coat [draculass]",
  "/obj/item/clothing/under/costume/drfreeze": "doctor freeze's jumpsuit [drfreeze]",
  "/obj/item/clothing/under/costume/lobster": "foam lobster suit [lobster]",
  "/obj/item/clothing/under/costume/gondola": "gondola hide suit [gondola]",
  "/obj/item/clothing/under/costume/skeleton": "skeleton jumpsuit [skeleton]",
  "/obj/item/clothing/under/costume/mech_suit/white": "white mech pilot's suit [white_mech_suit]",
  "/obj/item/clothing/under/costume/mech_suit/blue": "blue mech pilot's suit [blue_mech_suit]",
  "/obj/item/clothing/under/costume/mech_suit": "red mech pilot's suit [red_mech_suit]",
  "/obj/item/clothing/under/costume/russian_officer": "Russian officer's uniform [hostanclothes]",
  "/obj/item/clothing/under/costume/jackbros": "jack bros outfit [JackFrostUniform]",
  "/obj/item/clothing/under/costume/yakuza": "tojo clan pants [MajimaPants]",
  "/obj/item/clothing/under/costume/dutch": "dutch's suit [DutchUniform]",
  "/obj/item/clothing/under/costume/swagoutfit": "Swag outfit [SwagOutfit]",
  "/obj/item/clothing/under/costume/referee": "referee uniform [referee]",
  "/obj/item/clothing/under/costume": "under []",
  "/obj/item/clothing/under/misc/pj/red": "PJs [red_pyjamas]",
  "/obj/item/clothing/under/misc/pj/blue": "PJs [blue_pyjamas]",
  "/obj/item/clothing/under/misc/pj": "PJs []",
  "/obj/item/clothing/under/misc/patriotsuit": "Patriotic Suit [ek]",
  "/obj/item/clothing/under/misc/mailman": "mailman's jumpsuit [mailman]",
  "/obj/item/clothing/under/misc/psyche": "psychedelic jumpsuit [psyche]",
  "/obj/item/clothing/under/misc/vice_officer": "vice officer's jumpsuit [vice]",
  "/obj/item/clothing/under/misc/adminsuit": "administrative cybernetic jumpsuit [syndicate]",
  "/obj/item/clothing/under/misc/burial": "burial garments [burial]",
  "/obj/item/clothing/under/misc/overalls": "laborer's overalls [overalls]",
  "/obj/item/clothing/under/misc/assistantformal": "assistant's formal uniform [assistant_formal]",
  "/obj/item/clothing/under/misc/durathread": "durathread jumpsuit [durathread]",
  "/obj/item/clothing/under/misc/bouncer": "bouncer uniform [bouncer]",
  "/obj/item/clothing/under/misc/coordinator": "coordinator jumpsuit [captain_parade]",
  "/obj/item/clothing/under/misc": "under []",
  "/obj/item/clothing/under/pants/classicjeans": "classic jeans [jeansclassic]",
  "/obj/item/clothing/under/pants/mustangjeans": "Must Hang jeans [jeansmustang]",
  "/obj/item/clothing/under/pants/blackjeans": "black jeans [jeansblack]",
  "/obj/item/clothing/under/pants/youngfolksjeans": "Young Folks jeans [jeansyoungfolks]",
  "/obj/item/clothing/under/pants/white": "white pants [whitepants]",
  "/obj/item/clothing/under/pants/red": "red pants [redpants]",
  "/obj/item/clothing/under/pants/black": "black pants [blackpants]",
  "/obj/item/clothing/under/pants/tan": "tan pants [tanpants]",
  "/obj/item/clothing/under/pants/track": "track pants [trackpants]",
  "/obj/item/clothing/under/pants/jeans": "jeans [jeans]",
  "/obj/item/clothing/under/pants/khaki": "khaki pants [khaki]",
  "/obj/item/clothing/under/pants/camo": "camo pants [camopants]",
  "/obj/item/clothing/under/pants": "under []",
  "/obj/item/clothing/under/shorts/red": "red athletic shorts [redshorts]",
  "/obj/item/clothing/under/shorts/green": "green athletic shorts [greenshorts]",
  "/obj/item/clothing/under/shorts/blue": "blue athletic shorts [blueshorts]",
  "/obj/item/clothing/under/shorts/black": "black athletic shorts [blackshorts]",
  "/obj/item/clothing/under/shorts/grey": "grey athletic shorts [greyshorts]",
  "/obj/item/clothing/under/shorts/purple": "purple athletic shorts [purpleshorts]",
  "/obj/item/clothing/under/shorts": "athletic shorts []",
  "/obj/item/clothing/under/dress/sundress": "sundress [sundress]",
  "/obj/item/clothing/under/dress/blacktango": "black tango dress [black_tango]",
  "/obj/item/clothing/under/dress/striped": "striped dress [striped_dress]",
  "/obj/item/clothing/under/dress/sailor": "sailor dress [sailor_dress]",
  "/obj/item/clothing/under/dress/wedding_dress": "wedding dress [wedding_dress]",
  "/obj/item/clothing/under/dress/redeveninggown": "red evening gown [red_evening_gown]",
  "/obj/item/clothing/under/dress/skirt/blue": "blue skirt [blueskirt]",
  "/obj/item/clothing/under/dress/skirt/red": "red skirt [redskirt]",
  "/obj/item/clothing/under/dress/skirt/purple": "purple skirt [purpleskirt]",
  "/obj/item/clothing/under/dress/skirt/plaid/blue": "blue plaid skirt [plaid_blue]",
  "/obj/item/clothing/under/dress/skirt/plaid/purple": "purple plaid skirt [plaid_purple]",
  "/obj/item/clothing/under/dress/skirt/plaid/green": "green plaid skirt [plaid_green]",
  "/obj/item/clothing/under/dress/skirt/plaid": "red plaid skirt [plaid_red]",
  "/obj/item/clothing/under/dress/skirt": "black skirt [blackskirt]",
  "/obj/item/clothing/under/dress": "under []",
  "/obj/item/clothing/under/suit/white_on_white": "white suit [scratch]",
  "/obj/item/clothing/under/suit/white/skirt": "white suitskirt [white_suit_skirt]",
  "/obj/item/clothing/under/suit/white": "white suit [white_suit]",
  "/obj/item/clothing/under/suit/sl": "amish suit [sl_suit]",
  "/obj/item/clothing/under/suit/waiter": "waiter's outfit [waiter]",
  "/obj/item/clothing/under/suit/blacktwopiece": "black two piece suit [black_suit]",
  "/obj/item/clothing/under/suit/black/skirt": "black suitskirt [blacksuit_skirt]",
  "/obj/item/clothing/under/suit/black/female": "executive suit [black_suit_fem]",
  "/obj/item/clothing/under/suit/black": "black suit [blacksuit]",
  "/obj/item/clothing/under/suit/black_really/skirt": "executive suitskirt [really_black_suit_skirt]",
  "/obj/item/clothing/under/suit/black_really": "executive suit [really_black_suit]",
  "/obj/item/clothing/under/suit/green": "green suit [green_suit]",
  "/obj/item/clothing/under/suit/red": "red suit [red_suit]",
  "/obj/item/clothing/under/suit/charcoal": "charcoal suit [charcoal_suit]",
  "/obj/item/clothing/under/suit/navy": "navy suit [navy_suit]",
  "/obj/item/clothing/under/suit/burgundy": "burgundy suit [burgundy_suit]",
  "/obj/item/clothing/under/suit/checkered": "checkered suit [checkered_suit]",
  "/obj/item/clothing/under/suit/tan": "tan suit [tan_suit]",
  "/obj/item/clothing/under/suit/beige": "beige suit [beige_suit]",
  "/obj/item/clothing/under/suit/henchmen": "henchmen jumpsuit [henchmen]",
  "/obj/item/clothing/under/suit/tuxedo": "tuxedo [tuxedo]",
  "/obj/item/clothing/under/suit": "under []",
  "/obj/item/clothing/under/trek/command/next": "command uniform [trek_next_command]",
  "/obj/item/clothing/under/trek/command/ent": "command uniform [trek_ent_command]",
  "/obj/item/clothing/under/trek/command": "command uniform [trek_command]",
  "/obj/item/clothing/under/trek/engsec/next": "engsec uniform [trek_next_engsec]",
  "/obj/item/clothing/under/trek/engsec/ent": "engsec uniform [trek_ent_engsec]",
  "/obj/item/clothing/under/trek/engsec": "engsec uniform [trek_engsec]",
  "/obj/item/clothing/under/trek/medsci/next": "medsci uniform [trek_next_medsci]",
  "/obj/item/clothing/under/trek/medsci/ent": "medsci uniform [trek_ent_medsci]",
  "/obj/item/clothing/under/trek/medsci": "medsci uniform [trek_medsci]",
  "/obj/item/clothing/under/trek/q": "french marshall's uniform [trek_Q]",
  "/obj/item/clothing/under/trek": "under []",
  "/obj/item/clothing/under/plasmaman/centcom_commander": "CentCom commander plasma envirosuit [commander_envirosuit]",
  "/obj/item/clothing/under/plasmaman/centcom_official": "CentCom official plasma envirosuit [official_envirosuit]",
  "/obj/item/clothing/under/plasmaman/centcom_intern": "CentCom intern plasma envirosuit [intern_envirosuit]",
  "/obj/item/clothing/under/plasmaman/cargo": "cargo plasma envirosuit [cargo_envirosuit]",
  "/obj/item/clothing/under/plasmaman/mining": "mining plasma envirosuit [explorer_envirosuit]",
  "/obj/item/clothing/under/plasmaman/chef": "chef's plasma envirosuit [chef_envirosuit]",
  "/obj/item/clothing/under/plasmaman/enviroslacks": "enviroslacks [enviroslacks]",
  "/obj/item/clothing/under/plasmaman/chaplain": "chaplain's plasma envirosuit [chap_envirosuit]",
  "/obj/item/clothing/under/plasmaman/curator": "curator's plasma envirosuit [prototype_envirosuit]",
  "/obj/item/clothing/under/plasmaman/janitor": "janitor's plasma envirosuit [janitor_envirosuit]",
  "/obj/item/clothing/under/plasmaman/botany": "botany envirosuit [botany_envirosuit]",
  "/obj/item/clothing/under/plasmaman/mime": "mime envirosuit [mime_envirosuit]",
  "/obj/item/clothing/under/plasmaman/clown": "clown envirosuit [clown_envirosuit]",
  "/obj/item/clothing/under/plasmaman/prisoner": "prisoner envirosuit [prisoner_envirosuit]",
  "/obj/item/clothing/under/plasmaman/captain": "captain's plasma envirosuit [captain_envirosuit]",
  "/obj/item/clothing/under/plasmaman/head_of_personnel": "head of personnel's plasma envirosuit [hop_envirosuit]",
  "/obj/item/clothing/under/plasmaman/security/head_of_security": "head of security's envirosuit [hos_envirosuit]",
  "/obj/item/clothing/under/plasmaman/security/warden": "warden plasma envirosuit [warden_envirosuit]",
  "/obj/item/clothing/under/plasmaman/security": "security plasma envirosuit [security_envirosuit]",
  "/obj/item/clothing/under/plasmaman/chief_engineer": "chief engineer's plasma envirosuit [ce_envirosuit]",
  "/obj/item/clothing/under/plasmaman/chief_medical_officer": "chief medical officer's plasma envirosuit [cmo_envirosuit]",
  "/obj/item/clothing/under/plasmaman/research_director": "research director's plasma envirosuit [rd_envirosuit]",
  "/obj/item/clothing/under/plasmaman/engineering": "engineering plasma envirosuit [engineer_envirosuit]",
  "/obj/item/clothing/under/plasmaman/atmospherics": "atmospherics plasma envirosuit [atmos_envirosuit]",
  "/obj/item/clothing/under/plasmaman/medical": "medical plasma envirosuit [doctor_envirosuit]",
  "/obj/item/clothing/under/plasmaman/paramedic": "paramedic envirosuit [paramedic_envirosuit]",
  "/obj/item/clothing/under/plasmaman/science": "science plasma envirosuit [scientist_envirosuit]",
  "/obj/item/clothing/under/plasmaman/robotics": "robotics plasma envirosuit [roboticist_envirosuit]",
  "/obj/item/clothing/under/plasmaman/viro": "virology plasma envirosuit [virologist_envirosuit]",
  "/obj/item/clothing/under/plasmaman/genetics": "genetics plasma envirosuit [geneticist_envirosuit]",
  "/obj/item/clothing/under/plasmaman/chemist": "chemistry plasma envirosuit [chemist_envirosuit]",
  "/obj/item/clothing/under/plasmaman": "plasma envirosuit [plasmaman]",
  "/obj/item/clothing/under": "under []"
}
